import type { VocabEntry } from '../types';

/** [anglais, français, exemple?, traduction de l'exemple?] — l'ordre des thèmes = ordre d'apprentissage. */
type Raw = [string, string, string?, string?];

export const THEMES: Record<string, string> = {
  daily: 'Vie quotidienne',
  family: 'Famille et relations',
  home: 'Maison',
  food: 'Nourriture',
  work: 'Travail',
  it: 'Informatique',
  travel: 'Voyage',
  city: 'Ville',
  time: 'Temps et fréquence',
  health: 'Santé',
  feelings: 'Émotions et caractère',
  shopping: 'Achats et argent',
  weather: 'Météo et nature',
  leisure: 'Loisirs et sport',
  clothes: 'Vêtements',
  describe: 'Adjectifs utiles',
  ph_travel: 'Phrases utiles · Voyage',
  ph_work: 'Phrases utiles · Travail',
  ph_studies: 'Phrases utiles · Études',
  ph_culture: 'Phrases utiles · Films et séries',
  ph_people: 'Phrases utiles · Rencontres',
};

const RAW: Record<string, Raw[]> = {
  daily: [
    ['to wake up', 'se réveiller', 'I wake up at seven.', 'Je me réveille à sept heures.'],
    ['to get up', 'se lever', 'I get up early on weekdays.', 'Je me lève tôt en semaine.'],
    ['to have a shower', 'prendre une douche', 'I have a shower every morning.', 'Je prends une douche tous les matins.'],
    ['to get dressed', 's’habiller', 'I get dressed quickly.', 'Je m’habille vite.'],
    ['breakfast', 'petit-déjeuner', 'I never skip breakfast.', 'Je ne saute jamais le petit-déjeuner.'],
    ['lunch', 'déjeuner', 'We have lunch at noon.', 'Nous déjeunons à midi.'],
    ['dinner', 'dîner', 'Dinner is ready!', 'Le dîner est prêt !'],
    ['to go to bed', 'aller se coucher', 'I go to bed at eleven.', 'Je me couche à onze heures.'],
    ['to do the washing-up', 'faire la vaisselle', 'I do the washing-up after dinner.', 'Je fais la vaisselle après le dîner.'],
    ['to do the shopping', 'faire les courses', 'We do the shopping on Saturdays.', 'Nous faisons les courses le samedi.'],
    ['to clean', 'nettoyer', 'I clean the kitchen every day.', 'Je nettoie la cuisine tous les jours.'],
    ['to cook', 'cuisiner', 'My partner loves to cook.', 'Mon/ma partenaire adore cuisiner.'],
    ['to relax', 'se détendre', 'I relax on the sofa after work.', 'Je me détends sur le canapé après le travail.'],
    ['to be late', 'être en retard', 'Sorry, I’m late.', '{Désolé|Désolée}, je suis en retard.'],
    ['to be on time', 'être à l’heure', 'The train was on time.', 'Le train était à l’heure.'],
  ],
  family: [
    ['parents', 'parents', 'My parents live in Lyon.', 'Mes parents habitent à Lyon.'],
    ['brother', 'frère', 'My brother is older than me.', 'Mon frère est plus âgé que moi.'],
    ['sister', 'sœur', 'I have one sister.', 'J’ai une sœur.'],
    ['son', 'fils', 'Their son is five.', 'Leur fils a cinq ans.'],
    ['daughter', 'fille (enfant)', 'She has a daughter.', 'Elle a une fille.'],
    ['husband', 'mari', 'Her husband is a nurse.', 'Son mari est infirmier.'],
    ['wife', 'femme (épouse)', 'His wife works in a bank.', 'Sa femme travaille dans une banque.'],
    ['uncle', 'oncle', 'My uncle lives in Canada.', 'Mon oncle habite au Canada.'],
    ['aunt', 'tante', 'My aunt is very funny.', 'Ma tante est très drôle.'],
    ['cousin', 'cousin / cousine', 'I often see my cousins.', 'Je vois souvent mes cousins.'],
    ['grandparents', 'grands-parents', 'We visit our grandparents on Sundays.', 'Nous rendons visite à nos grands-parents le dimanche.'],
    ['friend', 'ami / amie', 'She’s my best friend.', 'C’est ma meilleure amie.'],
    ['neighbour', 'voisin / voisine', 'Our neighbours are very nice.', 'Nos voisins sont très gentils.'],
    ['to get married', 'se marier', 'They got married last year.', 'Ils se sont mariés l’an dernier.'],
    ['to grow up', 'grandir', 'I grew up in a small town.', 'J’ai grandi dans une petite ville.'],
  ],
  home: [
    ['flat', 'appartement', 'I live in a small flat.', 'J’habite dans un petit appartement.'],
    ['bedroom', 'chambre', 'My bedroom is quiet.', 'Ma chambre est calme.'],
    ['kitchen', 'cuisine (pièce)', 'The kitchen is next to the living room.', 'La cuisine est à côté du salon.'],
    ['living room', 'salon', 'We watch TV in the living room.', 'Nous regardons la télé dans le salon.'],
    ['bathroom', 'salle de bain', 'The bathroom is upstairs.', 'La salle de bain est en haut.'],
    ['garden', 'jardin', 'They have a big garden.', 'Ils ont un grand jardin.'],
    ['stairs', 'escalier', 'Take the stairs, the lift is broken.', 'Prends l’escalier, l’ascenseur est en panne.'],
    ['floor', 'étage / sol', 'I live on the third floor.', 'J’habite au troisième étage.'],
    ['furniture', 'meubles', 'We need new furniture.', 'Nous avons besoin de nouveaux meubles.'],
    ['fridge', 'frigo', 'There’s some milk in the fridge.', 'Il y a du lait dans le frigo.'],
    ['sofa', 'canapé', 'The cat is sleeping on the sofa.', 'Le chat dort sur le canapé.'],
    ['rent', 'loyer', 'The rent is very high in Paris.', 'Le loyer est très élevé à Paris.'],
    ['to move', 'déménager', 'We moved last month.', 'Nous avons déménagé le mois dernier.'],
    ['key', 'clé', 'I can’t find my keys.', 'Je ne trouve pas mes clés.'],
    ['to lock', 'fermer à clé', 'Don’t forget to lock the door.', 'N’oublie pas de fermer la porte à clé.'],
  ],
  food: [
    ['bread', 'pain', 'Can you buy some bread?', 'Tu peux acheter du pain ?'],
    ['cheese', 'fromage', 'France is famous for its cheese.', 'La France est célèbre pour son fromage.'],
    ['meat', 'viande', 'I don’t eat much meat.', 'Je ne mange pas beaucoup de viande.'],
    ['fish', 'poisson', 'We had fish for dinner.', 'Nous avons mangé du poisson au dîner.'],
    ['vegetables', 'légumes', 'Eat more vegetables!', 'Mange plus de légumes !'],
    ['fruit', 'fruits', 'I eat fruit every day.', 'Je mange des fruits tous les jours.'],
    ['chicken', 'poulet', 'The chicken is delicious.', 'Le poulet est délicieux.'],
    ['rice', 'riz', 'I’d like rice with my curry.', 'Je voudrais du riz avec mon curry.'],
    ['egg', 'œuf', 'I had two eggs for breakfast.', 'J’ai mangé deux œufs au petit-déjeuner.'],
    ['sugar', 'sucre', 'No sugar in my coffee, please.', 'Pas de sucre dans mon café, s’il te plaît.'],
    ['salt', 'sel', 'Can you pass me the salt?', 'Tu peux me passer le sel ?'],
    ['hungry', 'avoir faim', 'I’m hungry.', 'J’ai faim.'],
    ['thirsty', 'avoir soif', 'Are you thirsty?', 'Tu as soif ?'],
    ['delicious', 'délicieux', 'This cake is delicious.', 'Ce gâteau est délicieux.'],
    ['the bill', 'l’addition', 'Could we have the bill, please?', 'Pourrions-nous avoir l’addition, s’il vous plaît ?'],
    ['to order', 'commander', 'Are you ready to order?', 'Vous êtes prêts à commander ?'],
  ],
  work: [
    ['job', 'emploi / travail', 'I love my job.', 'J’adore mon travail.'],
    ['colleague', 'collègue', 'My colleagues are very helpful.', 'Mes collègues sont très serviables.'],
    ['manager', 'responsable / manager', 'I need to talk to my manager.', 'Je dois parler à mon responsable.'],
    ['meeting', 'réunion', 'The meeting starts at ten.', 'La réunion commence à dix heures.'],
    ['company', 'entreprise', 'She works for a big company.', 'Elle travaille pour une grande entreprise.'],
    ['office', 'bureau (lieu)', 'I go to the office three days a week.', 'Je vais au bureau trois jours par semaine.'],
    ['salary', 'salaire', 'The salary is good.', 'Le salaire est bon.'],
    ['to hire', 'embaucher', 'They want to hire two developers.', 'Ils veulent embaucher deux développeurs.'],
    ['deadline', 'date limite', 'The deadline is Friday.', 'La date limite est vendredi.'],
    ['task', 'tâche', 'I have three tasks to finish today.', 'J’ai trois tâches à finir aujourd’hui.'],
    ['customer', 'client', 'The customer is always right.', 'Le client a toujours raison.'],
    ['to work from home', 'télétravailler', 'I work from home on Fridays.', 'Je télétravaille le vendredi.'],
    ['busy', '{occupé|occupée}', 'I’m very busy this week.', 'Je suis très {occupé|occupée} cette semaine.'],
    ['day off', 'jour de congé', 'Tomorrow is my day off.', 'Demain, c’est mon jour de congé.'],
    ['job interview', 'entretien d’embauche', 'I have a job interview on Monday.', 'J’ai un entretien d’embauche lundi.'],
    ['to apply for', 'postuler à', 'I applied for a new job.', 'J’ai postulé à un nouveau poste.'],
  ],
  it: [
    ['computer', 'ordinateur', 'My computer is very slow.', 'Mon ordinateur est très lent.'],
    ['laptop', 'ordinateur portable', 'I take my laptop everywhere.', 'J’emporte mon portable partout.'],
    ['screen', 'écran', 'The screen is too small.', 'L’écran est trop petit.'],
    ['keyboard', 'clavier', 'I need a new keyboard.', 'J’ai besoin d’un nouveau clavier.'],
    ['password', 'mot de passe', 'Never share your password.', 'Ne partage jamais ton mot de passe.'],
    ['to log in', 'se connecter', 'I can’t log in to my account.', 'Je n’arrive pas à me connecter à mon compte.'],
    ['to download', 'télécharger', 'Download the file and open it.', 'Télécharge le fichier et ouvre-le.'],
    ['to upload', 'téléverser / mettre en ligne', 'Upload your photo here.', 'Mets ta photo en ligne ici.'],
    ['file', 'fichier', 'Can you send me the file?', 'Tu peux m’envoyer le fichier ?'],
    ['folder', 'dossier', 'Save it in this folder.', 'Enregistre-le dans ce dossier.'],
    ['to save', 'enregistrer', 'Don’t forget to save your work.', 'N’oublie pas d’enregistrer ton travail.'],
    ['to delete', 'supprimer', 'I deleted the email by mistake.', 'J’ai supprimé l’e-mail par erreur.'],
    ['network', 'réseau', 'The network is down.', 'Le réseau est en panne.'],
    ['update', 'mise à jour', 'Install the latest update.', 'Installe la dernière mise à jour.'],
    ['to crash', 'planter', 'The app crashed again.', 'L’application a encore planté.'],
    ['bug', 'bogue / bug', 'We found a bug in the code.', 'Nous avons trouvé un bug dans le code.'],
    ['to restart', 'redémarrer', 'Try to restart your computer.', 'Essaie de redémarrer ton ordinateur.'],
  ],
  travel: [
    ['flight', 'vol', 'My flight is delayed.', 'Mon vol est retardé.'],
    ['ticket', 'billet', 'I bought a train ticket.', 'J’ai acheté un billet de train.'],
    ['luggage', 'bagages', 'I only have hand luggage.', 'J’ai seulement un bagage à main.'],
    ['passport', 'passeport', 'Don’t forget your passport.', 'N’oublie pas ton passeport.'],
    ['to book', 'réserver', 'I booked a hotel room.', 'J’ai réservé une chambre d’hôtel.'],
    ['trip', 'voyage (court)', 'We went on a trip to Rome.', 'Nous avons fait un voyage à Rome.'],
    ['holiday', 'vacances', 'Where are you going on holiday?', 'Où pars-tu en vacances ?'],
    ['abroad', 'à l’étranger', 'I’d like to work abroad.', 'J’aimerais travailler à l’étranger.'],
    ['to miss', 'rater', 'I missed the bus.', 'J’ai raté le bus.'],
    ['platform', 'quai', 'The train leaves from platform 4.', 'Le train part du quai 4.'],
    ['delayed', 'retardé', 'The train is delayed by twenty minutes.', 'Le train a vingt minutes de retard.'],
    ['to check in', 'faire l’enregistrement', 'We can check in at two o’clock.', 'Nous pouvons nous enregistrer à quatorze heures.'],
    ['sightseeing', 'visite touristique', 'We did some sightseeing in London.', 'Nous avons visité Londres.'],
    ['map', 'carte / plan', 'Do you have a map of the city?', 'Avez-vous un plan de la ville ?'],
  ],
  city: [
    ['street', 'rue', 'I live on a quiet street.', 'J’habite dans une rue calme.'],
    ['traffic', 'circulation', 'There’s a lot of traffic today.', 'Il y a beaucoup de circulation aujourd’hui.'],
    ['traffic lights', 'feux de circulation', 'Turn left at the traffic lights.', 'Tourne à gauche aux feux.'],
    ['to turn left', 'tourner à gauche', 'Turn left after the bank.', 'Tourne à gauche après la banque.'],
    ['straight on', 'tout droit', 'Go straight on for 200 metres.', 'Va tout droit sur 200 mètres.'],
    ['corner', 'coin', 'The café is on the corner.', 'Le café est au coin.'],
    ['town hall', 'mairie', 'The town hall is in the main square.', 'La mairie est sur la place principale.'],
    ['chemist’s', 'pharmacie', 'Is there a chemist’s near here?', 'Y a-t-il une pharmacie près d’ici ?'],
    ['crowded', 'bondé', 'The metro is always crowded.', 'Le métro est toujours bondé.'],
    ['noisy', 'bruyant', 'My street is very noisy.', 'Ma rue est très bruyante.'],
    ['neighbourhood', 'quartier', 'It’s a nice neighbourhood.', 'C’est un quartier sympa.'],
    ['to get lost', 'se perdre', 'We got lost in the old town.', 'Nous nous sommes perdus dans la vieille ville.'],
  ],
  time: [
    ['always', 'toujours', 'She’s always on time.', 'Elle est toujours à l’heure.'],
    ['usually', 'd’habitude', 'I usually walk to work.', 'D’habitude, je vais au travail à pied.'],
    ['often', 'souvent', 'We often eat out.', 'Nous mangeons souvent au restaurant.'],
    ['sometimes', 'parfois', 'I sometimes work late.', 'Je travaille parfois tard.'],
    ['rarely', 'rarement', 'He rarely watches TV.', 'Il regarde rarement la télé.'],
    ['never', 'jamais', 'I never drink coffee at night.', 'Je ne bois jamais de café le soir.'],
    ['yesterday', 'hier', 'I called her yesterday.', 'Je l’ai appelée hier.'],
    ['tomorrow', 'demain', 'See you tomorrow!', 'À demain !'],
    ['tonight', 'ce soir', 'What are you doing tonight?', 'Que fais-tu ce soir ?'],
    ['ago', 'il y a (temps)', 'I moved here two years ago.', 'J’ai emménagé ici il y a deux ans.'],
    ['soon', 'bientôt', 'I’ll call you soon.', 'Je t’appelle bientôt.'],
    ['early', 'tôt', 'I get up early.', 'Je me lève tôt.'],
    ['late', 'tard / en retard', 'It’s late, let’s go home.', 'Il est tard, rentrons.'],
    ['still', 'encore / toujours', 'Are you still at work?', 'Tu es encore au travail ?'],
    ['already', 'déjà', 'I’ve already finished.', 'J’ai déjà fini.'],
    ['weekday', 'jour de semaine', 'The shop is open on weekdays.', 'Le magasin est ouvert en semaine.'],
  ],
  health: [
    ['headache', 'mal de tête', 'I have a headache.', 'J’ai mal à la tête.'],
    ['to hurt', 'faire mal', 'My back hurts.', 'J’ai mal au dos.'],
    ['sick', 'malade', 'I feel sick.', 'Je me sens malade / j’ai la nausée.'],
    ['a cold', 'un rhume', 'I’ve got a cold.', 'J’ai un rhume.'],
    ['fever', 'fièvre', 'She has a high fever.', 'Elle a beaucoup de fièvre.'],
    ['medicine', 'médicament', 'Take this medicine twice a day.', 'Prends ce médicament deux fois par jour.'],
    ['appointment', 'rendez-vous', 'I have a doctor’s appointment at five.', 'J’ai rendez-vous chez le médecin à dix-sept heures.'],
    ['to feel better', 'aller mieux', 'I feel better today.', 'Je vais mieux aujourd’hui.'],
    ['tired', '{fatigué|fatiguée}', 'I’m really tired.', 'Je suis vraiment {fatigué|fatiguée}.'],
    ['to rest', 'se reposer', 'You should rest.', 'Tu devrais te reposer.'],
    ['healthy', 'en bonne santé / sain', 'Try to eat healthy food.', 'Essaie de manger sainement.'],
    ['to break', 'casser', 'He broke his leg skiing.', 'Il s’est cassé la jambe au ski.'],
  ],
  feelings: [
    ['happy', '{heureux|heureuse} / {content|contente}', 'I’m happy to see you.', 'Je suis {content|contente} de te voir.'],
    ['sad', 'triste', 'Why are you sad?', 'Pourquoi es-tu triste ?'],
    ['angry', 'en colère', 'My boss was angry.', 'Mon patron était en colère.'],
    ['worried', '{inquiet|inquiète}', 'I’m worried about the exam.', 'Je suis {inquiet|inquiète} pour l’examen.'],
    ['scared', '{effrayé|effrayée} / avoir peur', 'I’m scared of spiders.', 'J’ai peur des araignées.'],
    ['bored', 's’ennuyer', 'I’m bored.', 'Je m’ennuie.'],
    ['excited', '{impatient|impatiente} / enthousiaste', 'I’m excited about the trip.', 'J’ai hâte de faire ce voyage.'],
    ['nervous', '{nerveux|nerveuse} / {stressé|stressée}', 'I’m nervous before interviews.', 'Je suis {stressé|stressée} avant les entretiens.'],
    ['proud', '{fier|fière}', 'I’m proud of you.', 'Je suis {fier|fière} de toi.'],
    ['kind', 'gentil', 'That’s very kind of you.', 'C’est très gentil de ta part.'],
    ['shy', 'timide', 'He’s a bit shy.', 'Il est un peu timide.'],
    ['funny', 'drôle', 'Your brother is so funny.', 'Ton frère est tellement drôle.'],
    ['lazy', '{paresseux|paresseuse}', 'I feel lazy today.', 'Je me sens {paresseux|paresseuse} aujourd’hui.'],
    ['surprised', '{surpris|surprise}', 'I was surprised by the news.', 'J’ai été {surpris|surprise} par la nouvelle.'],
  ],
  shopping: [
    ['cheap', 'bon marché', 'This shop is cheap.', 'Ce magasin n’est pas cher.'],
    ['expensive', 'cher', 'Paris is expensive.', 'Paris est cher.'],
    ['price', 'prix', 'What’s the price?', 'Quel est le prix ?'],
    ['to pay', 'payer', 'Can I pay by card?', 'Je peux payer par carte ?'],
    ['cash', 'espèces', 'I don’t have any cash.', 'Je n’ai pas d’espèces.'],
    ['to spend', 'dépenser', 'I spend too much money on clothes.', 'Je dépense trop d’argent en vêtements.'],
    ['to save money', 'économiser', 'I’m trying to save money.', 'J’essaie d’économiser.'],
    ['to borrow', 'emprunter', 'Can I borrow your pen?', 'Je peux emprunter ton stylo ?'],
    ['to lend', 'prêter', 'Can you lend me ten euros?', 'Tu peux me prêter dix euros ?'],
    ['receipt', 'ticket de caisse', 'Keep the receipt.', 'Garde le ticket de caisse.'],
    ['sale', 'soldes / vente', 'These shoes were on sale.', 'Ces chaussures étaient en soldes.'],
    ['to try on', 'essayer (vêtement)', 'Can I try it on?', 'Je peux l’essayer ?'],
    ['size', 'taille', 'What size are you?', 'Quelle taille fais-tu ?'],
  ],
  weather: [
    ['sunny', 'ensoleillé', 'It’s sunny today.', 'Il fait beau aujourd’hui.'],
    ['cloudy', 'nuageux', 'It’s cloudy and grey.', 'C’est nuageux et gris.'],
    ['to rain', 'pleuvoir', 'It rains a lot in Brittany.', 'Il pleut beaucoup en Bretagne.'],
    ['snow', 'neige', 'There was snow in the mountains.', 'Il y avait de la neige en montagne.'],
    ['wind', 'vent', 'The wind is very strong.', 'Le vent est très fort.'],
    ['hot', 'chaud', 'It’s too hot in here.', 'Il fait trop chaud ici.'],
    ['cold', 'froid', 'It’s cold outside.', 'Il fait froid dehors.'],
    ['warm', 'doux / tiède', 'It’s warm for October.', 'Il fait doux pour octobre.'],
    ['storm', 'orage / tempête', 'There was a storm last night.', 'Il y a eu un orage hier soir.'],
    ['weather forecast', 'prévisions météo', 'Check the weather forecast.', 'Regarde la météo.'],
    ['beach', 'plage', 'Let’s go to the beach.', 'Allons à la plage.'],
    ['countryside', 'campagne', 'I prefer the countryside.', 'Je préfère la campagne.'],
  ],
  leisure: [
    ['free time', 'temps libre', 'What do you do in your free time?', 'Que fais-tu pendant ton temps libre ?'],
    ['to go for a walk', 'se promener', 'Let’s go for a walk.', 'Allons nous promener.'],
    ['to play football', 'jouer au foot', 'I play football on Wednesdays.', 'Je joue au foot le mercredi.'],
    ['gym', 'salle de sport', 'I go to the gym twice a week.', 'Je vais à la salle deux fois par semaine.'],
    ['to run', 'courir', 'I run every morning.', 'Je cours tous les matins.'],
    ['to swim', 'nager', 'Can you swim?', 'Tu sais nager ?'],
    ['series', 'série', 'I’m watching a great series.', 'Je regarde une super série.'],
    ['to hang out', 'traîner (avec des amis)', 'We hang out at the weekend.', 'On traîne ensemble le week-end.'],
    ['concert', 'concert', 'We went to a concert last night.', 'Nous sommes allés à un concert hier soir.'],
    ['hobby', 'loisir / passe-temps', 'Photography is my hobby.', 'La photo est mon passe-temps.'],
    ['to enjoy', 'apprécier / aimer', 'I really enjoyed the film.', 'J’ai vraiment aimé le film.'],
    ['match', 'match', 'Did you watch the match?', 'Tu as regardé le match ?'],
  ],
  clothes: [
    ['shirt', 'chemise', 'He’s wearing a blue shirt.', 'Il porte une chemise bleue.'],
    ['trousers', 'pantalon', 'These trousers are too long.', 'Ce pantalon est trop long.'],
    ['jacket', 'veste', 'Take a jacket, it’s cold.', 'Prends une veste, il fait froid.'],
    ['shoes', 'chaussures', 'I need new shoes.', 'J’ai besoin de nouvelles chaussures.'],
    ['dress', 'robe', 'She bought a red dress.', 'Elle a acheté une robe rouge.'],
    ['coat', 'manteau', 'Put your coat on.', 'Mets ton manteau.'],
    ['to wear', 'porter (vêtement)', 'I wear glasses.', 'Je porte des lunettes.'],
    ['suit', 'costume', 'He wears a suit to work.', 'Il porte un costume au travail.'],
    ['trainers', 'baskets', 'I always wear trainers.', 'Je porte toujours des baskets.'],
  ],
  describe: [
    ['easy', 'facile', 'This exercise is easy.', 'Cet exercice est facile.'],
    ['difficult', 'difficile', 'English grammar isn’t that difficult.', 'La grammaire anglaise n’est pas si difficile.'],
    ['important', 'important', 'This meeting is important.', 'Cette réunion est importante.'],
    ['useful', 'utile', 'This app is really useful.', 'Cette application est vraiment utile.'],
    ['boring', 'ennuyeux', 'The film was boring.', 'Le film était ennuyeux.'],
    ['interesting', 'intéressant', 'That’s an interesting idea.', 'C’est une idée intéressante.'],
    ['quiet', 'calme', 'The library is quiet.', 'La bibliothèque est calme.'],
    ['busy', 'animé / chargé', 'The city centre is busy on Saturdays.', 'Le centre-ville est animé le samedi.'],
    ['empty', 'vide', 'The fridge is empty.', 'Le frigo est vide.'],
    ['full', 'plein', 'The train was full.', 'Le train était plein.'],
    ['wrong', 'faux / mauvais', 'Sorry, wrong number.', '{Désolé|Désolée}, mauvais numéro.'],
    ['right', 'juste / exact', 'You’re right.', 'Tu as raison.'],
    ['ready', '{prêt|prête}', 'Are you ready?', 'Tu es {prêt|prête} ?'],
    ['free', 'libre / gratuit', 'The museum is free on Sundays.', 'Le musée est gratuit le dimanche.'],
    ['safe', 'sûr / en sécurité', 'Is this area safe at night?', 'Ce quartier est-il sûr la nuit ?'],
    ['dangerous', 'dangereux', 'This road is dangerous.', 'Cette route est dangereuse.'],
  ],
  // Phrases toutes faites, proposées en priorité selon les objectifs choisis à l'inscription.
  ph_travel: [
    ['Where is the nearest station?', 'Où est la gare la plus proche ?'],
    ['I’d like to check in, please.', 'Je voudrais m’enregistrer, s’il vous plaît.'],
    ['How much is a ticket to the city centre?', 'Combien coûte un billet pour le centre-ville ?'],
    ['Could you take a photo of us?', 'Pourriez-vous nous prendre en photo ?'],
    ['Is breakfast included?', 'Le petit-déjeuner est-il compris ?'],
    ['Can I have the bill, please?', 'L’addition, s’il vous plaît.'],
    ['My flight has been delayed.', 'Mon vol a été retardé.'],
    ['I’m looking for this address.', 'Je cherche cette adresse.'],
    ['Do you have a table for two?', 'Avez-vous une table pour deux ?'],
    ['I’ve lost my passport.', 'J’ai perdu mon passeport.'],
  ],
  ph_work: [
    ['Let’s schedule a meeting.', 'Planifions une réunion.'],
    ['Could you send me the file?', 'Pourrais-tu m’envoyer le fichier ?'],
    ['I’ll get back to you tomorrow.', 'Je reviens vers toi demain.'],
    ['Sorry, I didn’t catch that.', '{Désolé|Désolée}, je n’ai pas bien compris.'],
    ['What’s the deadline?', 'Quelle est la date limite ?'],
    ['I’m working on it.', 'Je suis dessus.'],
    ['Can we move the call to Friday?', 'Peut-on déplacer l’appel à vendredi ?'],
    ['I agree with you.', 'Je suis d’accord avec toi.'],
    ['Let me check and confirm.', 'Je vérifie et je confirme.'],
    ['Thanks for your help.', 'Merci pour ton aide.'],
  ],
  ph_studies: [
    ['Could you repeat the question?', 'Pourriez-vous répéter la question ?'],
    ['What does this word mean?', 'Que veut dire ce mot ?'],
    ['How do you spell it?', 'Comment ça s’écrit ?'],
    ['I have an exam next week.', 'J’ai un examen la semaine prochaine.'],
    ['Can I hand in my homework tomorrow?', 'Puis-je rendre mes devoirs demain ?'],
    ['I don’t understand this part.', 'Je ne comprends pas cette partie.'],
    ['Let’s study together.', 'Révisons ensemble.'],
    ['When is the deadline for the essay?', 'Quelle est la date limite pour la dissertation ?'],
    ['Can you speak more slowly, please?', 'Pouvez-vous parler plus lentement, s’il vous plaît ?'],
    ['I need to revise for the test.', 'Je dois réviser pour le contrôle.'],
  ],
  ph_culture: [
    ['What are you watching at the moment?', 'Qu’est-ce que tu regardes en ce moment ?'],
    ['The ending was amazing.', 'La fin était incroyable.'],
    ['No spoilers, please!', 'Pas de spoilers, s’il te plaît !'],
    ['It’s based on a true story.', 'C’est inspiré d’une histoire vraie.'],
    ['I watch it with English subtitles.', 'Je le regarde avec les sous-titres en anglais.'],
    ['Who is your favourite singer?', 'Qui est ton chanteur préféré ?'],
    ['The new season comes out next month.', 'La nouvelle saison sort le mois prochain.'],
    ['I couldn’t stop watching.', 'Je ne pouvais plus m’arrêter de regarder.'],
    ['What is it about?', 'De quoi ça parle ?'],
    ['I highly recommend it.', 'Je le recommande vivement.'],
  ],
  ph_people: [
    ['Nice to meet you.', '{Enchanté|Enchantée} de faire ta connaissance.'],
    ['Where are you from?', 'D’où viens-tu ?'],
    ['What do you do for a living?', 'Qu’est-ce que tu fais dans la vie ?'],
    ['How long have you lived here?', 'Depuis combien de temps vis-tu ici ?'],
    ['Do you want to grab a coffee?', 'Tu veux aller boire un café ?'],
    ['That sounds great!', 'Ça a l’air génial !'],
    ['What do you do in your free time?', 'Qu’est-ce que tu fais pendant ton temps libre ?'],
    ['Let’s keep in touch.', 'Restons en contact.'],
    ['It was nice talking to you.', 'C’était sympa de discuter avec toi.'],
    ['See you soon!', 'À bientôt !'],
  ],
};

const slug = (s: string) =>
  s.toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

export const VOCAB_A2: VocabEntry[] = Object.entries(RAW).flatMap(([theme, rows]) =>
  rows.map(([en, fr, example, exampleFr]) => ({
    // l'id inclut le thème : « busy » existe dans deux thèmes avec deux sens
    id: `a2-${theme}-${slug(en)}`,
    en,
    fr,
    cefr: 'A2' as const,
    theme,
    example,
    exampleFr,
  })),
);
