import type { IrregularVerb } from '../types';

/** Les verbes irréguliers les plus fréquents, par ordre d'importance. [base, past, participle, français] */
const RAW: [string, string, string, string][] = [
  ['be', 'was / were', 'been', 'être'],
  ['have', 'had', 'had', 'avoir'],
  ['do', 'did', 'done', 'faire'],
  ['say', 'said', 'said', 'dire'],
  ['go', 'went', 'gone', 'aller'],
  ['get', 'got', 'got / gotten', 'obtenir, devenir'],
  ['make', 'made', 'made', 'fabriquer, faire'],
  ['know', 'knew', 'known', 'savoir, connaître'],
  ['think', 'thought', 'thought', 'penser'],
  ['take', 'took', 'taken', 'prendre'],
  ['see', 'saw', 'seen', 'voir'],
  ['come', 'came', 'come', 'venir'],
  ['give', 'gave', 'given', 'donner'],
  ['find', 'found', 'found', 'trouver'],
  ['tell', 'told', 'told', 'raconter, dire à'],
  ['become', 'became', 'become', 'devenir'],
  ['leave', 'left', 'left', 'partir, quitter'],
  ['feel', 'felt', 'felt', 'ressentir'],
  ['put', 'put', 'put', 'mettre'],
  ['bring', 'brought', 'brought', 'apporter'],
  ['begin', 'began', 'begun', 'commencer'],
  ['keep', 'kept', 'kept', 'garder'],
  ['hold', 'held', 'held', 'tenir'],
  ['write', 'wrote', 'written', 'écrire'],
  ['stand', 'stood', 'stood', 'être debout'],
  ['hear', 'heard', 'heard', 'entendre'],
  ['let', 'let', 'let', 'laisser'],
  ['mean', 'meant', 'meant', 'signifier'],
  ['set', 'set', 'set', 'régler, fixer'],
  ['meet', 'met', 'met', 'rencontrer'],
  ['run', 'ran', 'run', 'courir'],
  ['pay', 'paid', 'paid', 'payer'],
  ['sit', 'sat', 'sat', 's’asseoir'],
  ['speak', 'spoke', 'spoken', 'parler'],
  ['lose', 'lost', 'lost', 'perdre'],
  ['understand', 'understood', 'understood', 'comprendre'],
  ['buy', 'bought', 'bought', 'acheter'],
  ['send', 'sent', 'sent', 'envoyer'],
  ['build', 'built', 'built', 'construire'],
  ['spend', 'spent', 'spent', 'dépenser, passer (du temps)'],
  ['read', 'read', 'read', 'lire'],
  ['grow', 'grew', 'grown', 'grandir, pousser'],
  ['win', 'won', 'won', 'gagner'],
  ['teach', 'taught', 'taught', 'enseigner'],
  ['catch', 'caught', 'caught', 'attraper'],
  ['fall', 'fell', 'fallen', 'tomber'],
  ['cut', 'cut', 'cut', 'couper'],
  ['sell', 'sold', 'sold', 'vendre'],
  ['eat', 'ate', 'eaten', 'manger'],
  ['drink', 'drank', 'drunk', 'boire'],
  ['drive', 'drove', 'driven', 'conduire'],
  ['break', 'broke', 'broken', 'casser'],
  ['choose', 'chose', 'chosen', 'choisir'],
  ['forget', 'forgot', 'forgotten', 'oublier'],
  ['sleep', 'slept', 'slept', 'dormir'],
  ['wear', 'wore', 'worn', 'porter (vêtement)'],
  ['fly', 'flew', 'flown', 'voler (en avion)'],
  ['swim', 'swam', 'swum', 'nager'],
  ['sing', 'sang', 'sung', 'chanter'],
  ['draw', 'drew', 'drawn', 'dessiner'],
  ['throw', 'threw', 'thrown', 'lancer'],
  ['steal', 'stole', 'stolen', 'voler (dérober)'],
  ['hide', 'hid', 'hidden', 'cacher'],
  ['ride', 'rode', 'ridden', 'monter (vélo, cheval)'],
  ['wake', 'woke', 'woken', 'se réveiller'],
  ['lend', 'lent', 'lent', 'prêter'],
  ['feed', 'fed', 'fed', 'nourrir'],
  ['fight', 'fought', 'fought', 'se battre'],
  ['hit', 'hit', 'hit', 'frapper'],
  ['hurt', 'hurt', 'hurt', 'blesser, faire mal'],
  ['shut', 'shut', 'shut', 'fermer'],
  ['cost', 'cost', 'cost', 'coûter'],
  ['forgive', 'forgave', 'forgiven', 'pardonner'],
  ['lie', 'lay', 'lain', 's’allonger'],
  ['ring', 'rang', 'rung', 'sonner'],
  ['rise', 'rose', 'risen', 'se lever, monter'],
  ['shake', 'shook', 'shaken', 'secouer'],
  ['shine', 'shone', 'shone', 'briller'],
  ['show', 'showed', 'shown', 'montrer'],
  ['sink', 'sank', 'sunk', 'couler'],
  ['stick', 'stuck', 'stuck', 'coller'],
  ['strike', 'struck', 'struck', 'frapper, faire grève'],
  ['swear', 'swore', 'sworn', 'jurer'],
  ['tear', 'tore', 'torn', 'déchirer'],
  ['bite', 'bit', 'bitten', 'mordre'],
  ['blow', 'blew', 'blown', 'souffler'],
  ['dig', 'dug', 'dug', 'creuser'],
  ['freeze', 'froze', 'frozen', 'geler'],
  ['hang', 'hung', 'hung', 'accrocher'],
  ['lead', 'led', 'led', 'mener'],
];

export const IRREGULAR_VERBS: IrregularVerb[] = RAW.map(([base, past, participle, fr], i) => ({
  id: base,
  base,
  past,
  participle,
  fr,
  // Les 50 premiers sont essentiels dès A2, les suivants arrivent en B1.
  cefr: i < 50 ? 'A2' : 'B1',
}));
