import { vocabFromRows, type VocabRow } from '../level';

/** Thèmes du vocabulaire C2 (clés préfixées par le niveau) dans l'ordre d'apprentissage. */
export const THEMES_C2: Record<string, string> = {
  c2_argument: 'Pensée et argumentation',
  c2_communication: 'Communication et nuance',
  c2_character: 'Caractère et comportement',
  c2_work: 'Travail et organisation',
  c2_culture: 'Arts et culture',
  c2_nature: 'Nature et environnement',
};

/** Les exemples reprennent le mot exact quand c'est naturel, pour alimenter les exercices à trous générés. */
const ROWS: Record<string, VocabRow[]> = {
  c2_argument: [
    ['tenuous', 'ténu, fragile (lien, argument)', 'The link between the two events is tenuous at best.', 'Le lien entre les deux événements est au mieux ténu.'],
    ['compelling', 'convaincant, irrésistible', 'She made a compelling case for a four-day week.', 'Elle a présenté des arguments convaincants en faveur de la semaine de quatre jours.'],
    ['spurious', 'fallacieux, sans fondement', 'The report draws a spurious connection between coffee and creativity.', 'Le rapport établit un lien fallacieux entre le café et la créativité.'],
    ['to substantiate', 'étayer, justifier', 'Can you substantiate that claim with data?', 'Peux-tu étayer cette affirmation avec des données ?'],
    ['to refute', 'réfuter', 'The team was able to refute every objection.', 'L’équipe a pu réfuter chaque objection.'],
    ['to concede', 'concéder, admettre', 'I concede that the plan is ambitious.', 'Je concède que le projet est ambitieux.'],
    ['a premise', 'une prémisse', 'The whole argument rests on a false premise.', 'Tout le raisonnement repose sur une prémisse fausse.'],
    ['a fallacy', 'une idée fausse, un sophisme', 'It is a common fallacy that bigger is always better.', 'C’est une idée fausse répandue que plus grand est toujours mieux.'],
    ['a caveat', 'une réserve, une mise en garde', 'The results are promising, with one important caveat.', 'Les résultats sont prometteurs, avec une réserve importante.'],
    ['cogent', 'solide, pertinent (argument)', 'He gave a cogent explanation of the delay.', 'Il a donné une explication solide du retard.'],
    ['to undermine', 'saper, affaiblir', 'One careless mistake can undermine months of work.', 'Une seule erreur d’inattention peut saper des mois de travail.'],
    ['to corroborate', 'corroborer', 'A second study seems to corroborate these findings.', 'Une deuxième étude semble corroborer ces résultats.'],
    ['a counterargument', 'un contre-argument', 'A good essay anticipates the main counterargument.', 'Une bonne dissertation anticipe le principal contre-argument.'],
    ['moot', 'discutable, sans objet', 'Whether we could have won is now a moot point.', 'Savoir si nous aurions pu gagner est désormais une question sans objet.'],
    ['to posit', 'poser comme hypothèse', 'The author posits that cities will shrink.', 'L’auteur pose l’hypothèse que les villes vont rétrécir.'],
    ['unwarranted', 'injustifié', 'Their concern turned out to be unwarranted.', 'Leur inquiétude s’est révélée injustifiée.'],
    ['a sweeping generalisation', 'une généralisation abusive', 'Saying all teenagers are lazy is a sweeping generalisation.', 'Dire que tous les adolescents sont paresseux est une généralisation abusive.'],
    ['a red herring', 'une fausse piste, une diversion', 'The question about the logo was a red herring.', 'La question sur le logo était une fausse piste.'],
    ['to weigh up', 'peser (le pour et le contre)', 'We need to weigh up the costs and benefits.', 'Il nous faut peser les coûts et les avantages.'],
    ['nuanced', 'nuancé', 'She gave a nuanced answer to a difficult question.', 'Elle a donné une réponse nuancée à une question difficile.'],
  ],
  c2_communication: [
    ['to allude to', 'faire allusion à', 'He alluded to a surprise without giving anything away.', 'Il a fait allusion à une surprise sans rien dévoiler.'],
    ['to insinuate', 'insinuer', 'Are you insinuating that I forgot on purpose?', 'Insinues-tu que j’ai oublié exprès ?'],
    ['tongue-in-cheek', 'au second degré, ironique', 'The review was written in a tongue-in-cheek style.', 'La critique était écrite au second degré.'],
    ['to beat about the bush', 'tourner autour du pot', 'Stop beating about the bush and tell me what happened.', 'Arrête de tourner autour du pot et dis-moi ce qui s’est passé.'],
    ['to get the gist', 'saisir l’essentiel', 'I didn’t understand every word, but I got the gist.', 'Je n’ai pas compris chaque mot, mais j’ai saisi l’essentiel.'],
    ['an understatement', 'un euphémisme, une litote', 'To call the hike tiring would be an understatement.', 'Dire que la randonnée était fatigante serait un euphémisme.'],
    ['to paraphrase', 'paraphraser', 'Let me paraphrase what you have just said.', 'Laisse-moi reformuler ce que tu viens de dire.'],
    ['succinct', 'succinct, concis', 'Keep your summary succinct: one page at most.', 'Garde ton résumé concis : une page au maximum.'],
    ['long-winded', 'interminable, verbeux', 'His long-winded introduction lasted twenty minutes.', 'Son introduction interminable a duré vingt minutes.'],
    ['articulate', 'qui s’exprime avec aisance', 'She is an articulate speaker, even under pressure.', 'Elle s’exprime avec aisance, même sous pression.'],
    ['to backtrack', 'faire marche arrière, se rétracter', 'The company had to backtrack on its new pricing.', 'L’entreprise a dû faire marche arrière sur sa nouvelle tarification.'],
    ['to hedge', 'rester évasif, ménager ses arrières', 'When asked for a date, the builder began to hedge.', 'Quand on lui a demandé une date, l’artisan est devenu évasif.'],
    ['to reiterate', 'réitérer', 'I would like to reiterate our thanks to the volunteers.', 'Je tiens à réitérer nos remerciements aux bénévoles.'],
    ['a rapport', 'une entente, une relation de confiance', 'Good teachers build a rapport with their students.', 'Les bons enseignants établissent une relation de confiance avec leurs élèves.'],
    ['to broach', 'aborder (un sujet délicat)', 'I didn’t know how to broach the subject of a pay rise.', 'Je ne savais pas comment aborder le sujet d’une augmentation.'],
    ['candid', 'franc, sincère', 'Thank you for your candid feedback.', 'Merci pour ton retour franc.'],
    ['evasive', 'évasif', 'His answers became increasingly evasive.', 'Ses réponses sont devenues de plus en plus évasives.'],
    ['to mince words', 'mâcher ses mots', 'She doesn’t mince words when she disagrees.', 'Elle ne mâche pas ses mots quand elle n’est pas d’accord.'],
    ['an innuendo', 'une insinuation, un sous-entendu', 'The comment was full of innuendo.', 'Le commentaire était plein de sous-entendus.'],
    ['to elaborate', 'développer, donner des détails', 'Could you elaborate on your second point?', 'Pourriez-vous développer votre deuxième point ?'],
  ],
  c2_character: [
    ['conscientious', 'consciencieux', 'She is a conscientious student who never misses a deadline.', 'C’est une élève consciencieuse qui ne manque jamais une échéance.'],
    ['diffident', 'réservé, qui manque d’assurance', 'He was diffident at first but soon relaxed.', 'Il était réservé au début, mais s’est vite détendu.'],
    ['magnanimous', 'magnanime', 'She was magnanimous in victory.', 'Elle s’est montrée magnanime dans la victoire.'],
    ['resilient', 'résilient, qui rebondit', 'Children are often more resilient than we think.', 'Les enfants sont souvent plus résilients qu’on ne le croit.'],
    ['meticulous', 'méticuleux', 'The restoration was carried out with meticulous care.', 'La restauration a été réalisée avec un soin méticuleux.'],
    ['outspoken', 'franc, qui a son franc-parler', 'He is an outspoken critic of the new design.', 'Il critique ouvertement le nouveau design.'],
    ['gregarious', 'sociable, grégaire', 'Our gregarious neighbour knows everyone on the street.', 'Notre voisin sociable connaît tout le monde dans la rue.'],
    ['aloof', 'distant', 'He seemed aloof, but he was simply shy.', 'Il semblait distant, mais il était simplement timide.'],
    ['headstrong', 'têtu, impétueux', 'As a headstrong teenager, she ignored all advice.', 'Adolescente têtue, elle ignorait tous les conseils.'],
    ['unassuming', 'modeste, sans prétention', 'Despite his fame, he remains unassuming.', 'Malgré sa célébrité, il reste sans prétention.'],
    ['thrifty', 'économe', 'My thrifty aunt repairs everything herself.', 'Ma tante économe répare tout elle-même.'],
    ['stingy', 'radin', 'Don’t be stingy with the cheese!', 'Ne sois pas radin avec le fromage !'],
    ['pushy', 'insistant, envahissant', 'The salesman was polite but rather pushy.', 'Le vendeur était poli mais assez insistant.'],
    ['nosy', 'curieux, indiscret', 'Our nosy neighbours always know who visits us.', 'Nos voisins indiscrets savent toujours qui nous rend visite.'],
    ['fickle', 'inconstant, versatile', 'Fashion is notoriously fickle.', 'La mode est notoirement versatile.'],
    ['level-headed', 'pondéré, équilibré', 'We need someone level-headed to lead the team.', 'Il nous faut quelqu’un de pondéré pour diriger l’équipe.'],
    ['tactful', 'plein de tact', 'It was a tactful way of saying no.', 'C’était une façon pleine de tact de dire non.'],
    ['complacent', 'suffisant, trop sûr de soi', 'After two wins, the team became complacent.', 'Après deux victoires, l’équipe s’est reposée sur ses lauriers.'],
    ['scrupulous', 'scrupuleux', 'He is scrupulous about giving credit to others.', 'Il veille scrupuleusement à reconnaître le mérite des autres.'],
    ['quick-witted', 'vif d’esprit', 'A quick-witted reply made the whole room laugh.', 'Une réplique vive a fait rire toute la salle.'],
  ],
  c2_work: [
    ['a bottleneck', 'un goulet d’étranglement', 'The approval process has become a bottleneck.', 'Le processus de validation est devenu un goulet d’étranglement.'],
    ['to streamline', 'rationaliser, simplifier', 'We need to streamline the ordering system.', 'Nous devons simplifier le système de commande.'],
    ['to delegate', 'déléguer', 'Good managers know when to delegate.', 'Les bons managers savent quand déléguer.'],
    ['a stakeholder', 'une partie prenante', 'All stakeholders were invited to the workshop.', 'Toutes les parties prenantes ont été invitées à l’atelier.'],
    ['to spearhead', 'piloter, être le fer de lance de', 'She will spearhead the new recycling project.', 'Elle pilotera le nouveau projet de recyclage.'],
    ['a setback', 'un revers, un contretemps', 'Despite an early setback, the launch went well.', 'Malgré un contretemps au début, le lancement s’est bien passé.'],
    ['to liaise with', 'assurer la liaison avec', 'You will liaise with our partners in Madrid.', 'Tu assureras la liaison avec nos partenaires à Madrid.'],
    ['a remit', 'une mission, un champ de compétence', 'Budget questions fall outside my remit.', 'Les questions budgétaires sortent de mon champ de compétence.'],
    ['to prioritise', 'hiérarchiser, donner la priorité à', 'Let’s prioritise the tasks that affect customers.', 'Donnons la priorité aux tâches qui concernent les clients.'],
    ['a stopgap', 'une solution provisoire, un bouche-trou', 'The spreadsheet is only a stopgap until the new software arrives.', 'Le tableur n’est qu’une solution provisoire en attendant le nouveau logiciel.'],
    ['to troubleshoot', 'diagnostiquer et résoudre', 'He spent the morning troubleshooting the printer.', 'Il a passé la matinée à dépanner l’imprimante.'],
    ['a track record', 'des antécédents, un historique', 'The firm has an excellent track record.', 'L’entreprise a d’excellents antécédents.'],
    ['to headhunt', 'recruter (un cadre) par approche directe', 'She was headhunted by a rival company.', 'Elle a été débauchée par une entreprise concurrente.'],
    ['a buy-in', 'une adhésion', 'Without staff buy-in, the reform will fail.', 'Sans l’adhésion du personnel, la réforme échouera.'],
    ['to touch base', 'faire le point, reprendre contact', 'Let’s touch base again on Friday.', 'Refaisons le point vendredi.'],
    ['a turnaround', 'un redressement, un délai de traitement', 'The turnaround for orders is now two days.', 'Le délai de traitement des commandes est désormais de deux jours.'],
    ['burnout', 'épuisement professionnel', 'Regular breaks help prevent burnout.', 'Des pauses régulières aident à prévenir l’épuisement professionnel.'],
    ['to overhaul', 'réviser en profondeur, refondre', 'The council plans to overhaul the bus network.', 'La mairie prévoit de refondre le réseau de bus.'],
    ['a deliverable', 'un livrable', 'The first deliverable is due at the end of the month.', 'Le premier livrable est attendu à la fin du mois.'],
    ['to pitch', 'présenter, proposer (une idée)', 'They pitched their idea to three investors.', 'Ils ont présenté leur idée à trois investisseurs.'],
  ],
  c2_culture: [
    ['a masterpiece', 'un chef-d’œuvre', 'Many consider the novel a masterpiece.', 'Beaucoup considèrent ce roman comme un chef-d’œuvre.'],
    ['poignant', 'poignant, émouvant', 'The film ends with a poignant scene at the station.', 'Le film se termine par une scène poignante à la gare.'],
    ['evocative', 'évocateur', 'Her evocative descriptions bring the village to life.', 'Ses descriptions évocatrices font revivre le village.'],
    ['derivative', 'peu original, sans originalité', 'The plot felt derivative of older thrillers.', 'L’intrigue semblait calquée sur des thrillers plus anciens.'],
    ['understated', 'sobre, tout en retenue', 'The actor gives an understated but powerful performance.', 'L’acteur livre une interprétation sobre mais puissante.'],
    ['a retrospective', 'une rétrospective', 'The gallery is holding a retrospective of her work.', 'La galerie organise une rétrospective de son œuvre.'],
    ['acclaimed', 'salué par la critique', 'The acclaimed director is working on a new series.', 'Le réalisateur salué par la critique travaille sur une nouvelle série.'],
    ['a cliffhanger', 'un suspense de fin d’épisode', 'Every episode ends on a cliffhanger.', 'Chaque épisode se termine sur un moment de suspense.'],
    ['highbrow', 'intellectuel, élitiste', 'The magazine is a little too highbrow for me.', 'Le magazine est un peu trop intellectuel pour moi.'],
    ['lowbrow', 'populaire, sans prétention intellectuelle', 'I enjoy lowbrow comedies on Friday nights.', 'J’aime les comédies populaires le vendredi soir.'],
    ['a pastiche', 'un pastiche', 'The song is a clever pastiche of 1960s pop.', 'La chanson est un habile pastiche de la pop des années 1960.'],
    ['to captivate', 'captiver', 'The storyteller managed to captivate the whole audience.', 'Le conteur a réussi à captiver tout le public.'],
    ['a connoisseur', 'un connaisseur', 'He is a connoisseur of early jazz.', 'C’est un connaisseur du jazz des débuts.'],
    ['an encore', 'un rappel, un bis', 'The audience demanded an encore.', 'Le public a réclamé un rappel.'],
    ['a protagonist', 'un protagoniste, un héros', 'The protagonist is a retired lighthouse keeper.', 'Le héros est un gardien de phare à la retraite.'],
    ['a premiere', 'une première (représentation)', 'The premiere took place in Edinburgh.', 'La première a eu lieu à Édimbourg.'],
    ['avant-garde', 'd’avant-garde', 'The festival showcases avant-garde theatre.', 'Le festival met en avant le théâtre d’avant-garde.'],
    ['a rendition', 'une interprétation (musicale)', 'Her rendition of the old folk song was stunning.', 'Son interprétation de la vieille chanson populaire était saisissante.'],
    ['to resonate', 'trouver un écho', 'The novel’s themes still resonate with young readers.', 'Les thèmes du roman trouvent encore un écho chez les jeunes lecteurs.'],
    ['a hidden gem', 'une pépite méconnue', 'This little museum is a hidden gem.', 'Ce petit musée est une pépite méconnue.'],
  ],
  c2_nature: [
    ['pristine', 'intact, immaculé', 'The island’s beaches are still pristine.', 'Les plages de l’île sont encore intactes.'],
    ['a habitat', 'un habitat', 'The wetlands are a vital habitat for migrating birds.', 'Les zones humides sont un habitat vital pour les oiseaux migrateurs.'],
    ['to thrive', 'prospérer, s’épanouir', 'These plants thrive in poor, sandy soil.', 'Ces plantes prospèrent dans un sol pauvre et sablonneux.'],
    ['arid', 'aride', 'Few trees grow in this arid landscape.', 'Peu d’arbres poussent dans ce paysage aride.'],
    ['lush', 'luxuriant', 'After the rains, the valley turned lush and green.', 'Après les pluies, la vallée est devenue verte et luxuriante.'],
    ['a canopy', 'la canopée', 'Monkeys move through the forest canopy.', 'Les singes se déplacent dans la canopée.'],
    ['biodiversity', 'la biodiversité', 'Hedgerows help to protect biodiversity on farms.', 'Les haies contribuent à protéger la biodiversité dans les fermes.'],
    ['to deplete', 'épuiser (des ressources)', 'Overfishing has depleted the stocks of cod.', 'La surpêche a épuisé les stocks de cabillaud.'],
    ['sustainable', 'durable', 'The café only buys sustainable fish.', 'Le café n’achète que du poisson issu de la pêche durable.'],
    ['a drought', 'une sécheresse', 'The region is recovering from a long drought.', 'La région se remet d’une longue sécheresse.'],
    ['a downpour', 'une averse, un déluge', 'We were caught in a sudden downpour.', 'Nous avons été surpris par une averse soudaine.'],
    ['a gust', 'une rafale', 'A gust of wind blew the map out of my hands.', 'Une rafale de vent m’a arraché la carte des mains.'],
    ['to replenish', 'reconstituer, réapprovisionner', 'Spring rain helps replenish the reservoirs.', 'La pluie de printemps aide à reconstituer les réserves d’eau.'],
    ['a watershed', 'un tournant décisif (aussi : ligne de partage des eaux)', 'The discovery was a watershed in marine biology.', 'La découverte a marqué un tournant en biologie marine.'],
    ['rugged', 'escarpé, accidenté', 'The rugged coastline attracts experienced walkers.', 'Le littoral escarpé attire les randonneurs expérimentés.'],
    ['a vantage point', 'un point de vue, un poste d’observation', 'From this vantage point, you can see three valleys.', 'De ce point de vue, on voit trois vallées.'],
    ['to dwindle', 'diminuer, s’amenuiser', 'The number of bees has continued to dwindle.', 'Le nombre d’abeilles a continué de diminuer.'],
    ['an estuary', 'un estuaire', 'Seals can often be seen in the estuary.', 'On voit souvent des phoques dans l’estuaire.'],
    ['a carbon footprint', 'une empreinte carbone', 'Taking the train reduces your carbon footprint.', 'Prendre le train réduit ton empreinte carbone.'],
    ['to rewild', 'réensauvager', 'The estate plans to rewild part of its farmland.', 'Le domaine prévoit de réensauvager une partie de ses terres agricoles.'],
  ],
};

export const VOCAB_C2 = vocabFromRows('C2', ROWS);
