import type { VocabRow } from '../level';

/** Thèmes de vocabulaire C1 (clés préfixées par le niveau). */
export const THEMES_C1: Record<string, string> = {
  c1_work: 'Monde professionnel avancé',
  c1_society: 'Société et politique',
  c1_science: 'Recherche et argumentation',
  c1_environment: 'Environnement et ressources',
  c1_mind: 'Attitudes et caractère',
  c1_idioms: 'Expressions idiomatiques',
};

/**
 * L'exemple contient la forme de base du mot (sans « to ») : le générateur
 * de textes à trous la retrouve ainsi telle quelle dans la phrase.
 */
export const VOCAB_ROWS_C1: Record<string, VocabRow[]> = {
  c1_work: [
    ['to streamline', 'rationaliser, simplifier', 'We need to streamline the approval process.', 'Nous devons simplifier le processus de validation.'],
    ['to delegate', 'déléguer', 'A good manager knows when to delegate.', 'Un bon manager sait quand déléguer.'],
    ['stakeholder', 'partie prenante', 'Each stakeholder will be consulted before the launch.', 'Chaque partie prenante sera consultée avant le lancement.'],
    ['to meet a deadline', 'respecter un délai', 'It was hard to meet a deadline that tight.', 'Il était difficile de respecter un délai aussi serré.'],
    ['workload', 'charge de travail', 'Her workload has doubled since the merger.', 'Sa charge de travail a doublé depuis la fusion.'],
    ['to step down', 'se retirer (d’un poste), démissionner', 'The chairman will step down in June.', 'Le président se retirera en juin.'],
    ['burnout', 'épuisement professionnel', 'Long hours are a major cause of burnout.', 'Les longues journées sont une cause majeure d’épuisement professionnel.'],
    ['to headhunt', 'débaucher, recruter (un cadre)', 'Rival firms often try to headhunt top engineers.', 'Les entreprises concurrentes essaient souvent de débaucher les meilleurs ingénieurs.'],
    ['track record', 'bilan, antécédents', 'The candidate has an excellent track record in sales.', 'Le candidat a un excellent bilan dans la vente.'],
    ['to outsource', 'externaliser', 'Many firms outsource their IT support.', 'Beaucoup d’entreprises externalisent leur support informatique.'],
    ['turnover', 'rotation du personnel ; chiffre d’affaires', 'Staff turnover is unusually high this year.', 'La rotation du personnel est inhabituellement élevée cette année.'],
    ['leverage', 'moyen de pression, levier', 'Their strong sales give them leverage in negotiations.', 'Leurs bonnes ventes leur donnent un moyen de pression dans les négociations.'],
    ['to iron out', 'aplanir, régler (des difficultés)', 'We still need to iron out a few details.', 'Nous devons encore régler quelques détails.'],
    ['redundancy', 'licenciement économique', 'He accepted voluntary redundancy last year.', 'Il a accepté un départ volontaire l’année dernière.'],
    ['to touch base', 'faire le point, reprendre contact', 'Let’s touch base again after the meeting.', 'Faisons à nouveau le point après la réunion.'],
    ['bottleneck', 'goulet d’étranglement', 'Approval by the legal team has become a bottleneck.', 'La validation par le service juridique est devenue un goulet d’étranglement.'],
    ['to be accountable for', 'devoir rendre des comptes sur', 'Managers must be accountable for their decisions.', 'Les managers doivent rendre des comptes sur leurs décisions.'],
    ['incentive', 'incitation, mesure incitative', 'The bonus is a strong incentive to stay.', 'La prime est une forte incitation à rester.'],
    ['to fall through', 'échouer, tomber à l’eau', 'The deal could fall through at the last minute.', 'L’accord pourrait tomber à l’eau à la dernière minute.'],
    ['shortlist', 'liste restreinte (de candidats)', 'Three applicants made it onto the shortlist.', 'Trois candidats ont été retenus dans la liste restreinte.'],
  ],
  c1_society: [
    ['inequality', 'inégalité', 'Income inequality has widened over the past decade.', 'Les inégalités de revenus se sont creusées au cours de la dernière décennie.'],
    ['to tackle', 's’attaquer à (un problème)', 'The government has pledged to tackle homelessness.', 'Le gouvernement s’est engagé à s’attaquer au problème des sans-abri.'],
    ['grassroots', 'de terrain, citoyen', 'The campaign began as a grassroots movement.', 'La campagne a commencé comme un mouvement citoyen de terrain.'],
    ['to undermine', 'saper, affaiblir', 'Fake news can undermine trust in institutions.', 'Les fausses informations peuvent saper la confiance dans les institutions.'],
    ['turnout', 'taux de participation', 'Turnout was the lowest since 1945.', 'Le taux de participation a été le plus bas depuis 1945.'],
    ['to advocate', 'prôner, défendre', 'Many doctors advocate a tax on sugary drinks.', 'Beaucoup de médecins prônent une taxe sur les boissons sucrées.'],
    ['welfare state', 'État-providence', 'The welfare state was built after the war.', 'L’État-providence a été construit après la guerre.'],
    ['to enforce', 'faire appliquer', 'The police struggle to enforce the new law.', 'La police a du mal à faire appliquer la nouvelle loi.'],
    ['backlash', 'réaction hostile, retour de bâton', 'The decision provoked a fierce backlash online.', 'La décision a provoqué une violente réaction en ligne.'],
    ['to marginalise', 'marginaliser', 'Poor transport links marginalise rural areas.', 'Le manque de transports marginalise les zones rurales.'],
    ['scrutiny', 'examen minutieux, surveillance', 'The minister’s expenses came under scrutiny.', 'Les dépenses du ministre ont fait l’objet d’un examen minutieux.'],
    ['loophole', 'faille (juridique)', 'Some companies exploited a loophole to avoid tax.', 'Certaines entreprises ont exploité une faille pour éviter l’impôt.'],
    ['to uphold', 'faire respecter, maintenir', 'Judges must uphold the rule of law.', 'Les juges doivent faire respecter l’État de droit.'],
    ['social cohesion', 'cohésion sociale', 'Shared public spaces strengthen social cohesion.', 'Les espaces publics partagés renforcent la cohésion sociale.'],
    ['to curb', 'freiner, limiter', 'New measures aim to curb rising rents.', 'De nouvelles mesures visent à freiner la hausse des loyers.'],
    ['stance', 'position, prise de position', 'The party has softened its stance on immigration.', 'Le parti a assoupli sa position sur l’immigration.'],
    ['to lobby', 'faire pression (sur les décideurs)', 'Farmers continue to lobby for higher subsidies.', 'Les agriculteurs continuent de faire pression pour obtenir plus de subventions.'],
    ['bias', 'parti pris, biais', 'The report was accused of political bias.', 'Le rapport a été accusé de parti pris politique.'],
    ['to stem from', 'découler de, provenir de', 'Many of these problems stem from poverty.', 'Beaucoup de ces problèmes découlent de la pauvreté.'],
    ['landmark ruling', 'décision de justice historique', 'The court issued a landmark ruling on privacy.', 'Le tribunal a rendu une décision historique sur la vie privée.'],
  ],
  c1_science: [
    ['hypothesis', 'hypothèse', 'The data did not support the initial hypothesis.', 'Les données n’ont pas confirmé l’hypothèse initiale.'],
    ['to corroborate', 'corroborer', 'Further studies are needed to corroborate these findings.', 'D’autres études sont nécessaires pour corroborer ces résultats.'],
    ['findings', 'résultats (d’une étude)', 'The findings were published in a leading journal.', 'Les résultats ont été publiés dans une revue de premier plan.'],
    ['to draw a conclusion', 'tirer une conclusion', 'It is too early to draw a conclusion.', 'Il est trop tôt pour tirer une conclusion.'],
    ['flawed', 'entaché d’erreurs, biaisé', 'Critics argued that the method was flawed.', 'Les critiques ont soutenu que la méthode était biaisée.'],
    ['to shed light on', 'faire la lumière sur', 'The study may shed light on the causes of the disease.', 'L’étude pourrait faire la lumière sur les causes de la maladie.'],
    ['peer review', 'évaluation par les pairs', 'The paper is currently undergoing peer review.', 'L’article est en cours d’évaluation par les pairs.'],
    ['to outweigh', 'l’emporter sur', 'The benefits clearly outweigh the risks.', 'Les avantages l’emportent clairement sur les risques.'],
    ['sample size', 'taille de l’échantillon', 'The sample size was too small to be reliable.', 'L’échantillon était trop petit pour être fiable.'],
    ['to underpin', 'sous-tendre, étayer', 'Solid evidence must underpin any policy decision.', 'Toute décision politique doit reposer sur des preuves solides.'],
    ['correlation', 'corrélation', 'Correlation does not imply causation.', 'Corrélation n’est pas causalité.'],
    ['to discard', 'écarter, rejeter', 'Researchers had to discard incomplete data.', 'Les chercheurs ont dû écarter des données incomplètes.'],
    ['breakthrough', 'percée, avancée majeure', 'The vaccine was hailed as a breakthrough.', 'Le vaccin a été salué comme une avancée majeure.'],
    ['to point to', 'indiquer, laisser penser', 'The evidence seems to point to human error.', 'Les éléments semblent indiquer une erreur humaine.'],
    ['inconclusive', 'peu concluant', 'The results of the trial were inconclusive.', 'Les résultats de l’essai n’étaient pas concluants.'],
    ['to replicate', 'reproduire (une expérience)', 'Other teams failed to replicate the experiment.', 'D’autres équipes n’ont pas réussi à reproduire l’expérience.'],
    ['counterargument', 'contre-argument', 'A good essay addresses the main counterargument.', 'Une bonne dissertation répond au principal contre-argument.'],
    ['to substantiate', 'étayer, justifier', 'He was unable to substantiate his claims.', 'Il n’a pas pu étayer ses affirmations.'],
    ['rigorous', 'rigoureux', 'The study followed a rigorous methodology.', 'L’étude a suivi une méthodologie rigoureuse.'],
    ['by and large', 'dans l’ensemble', 'By and large, the experiment was a success.', 'Dans l’ensemble, l’expérience a été un succès.'],
  ],
  c1_environment: [
    ['carbon footprint', 'empreinte carbone', 'Flying less is the easiest way to reduce your carbon footprint.', 'Prendre moins l’avion est le moyen le plus simple de réduire ton empreinte carbone.'],
    ['to deplete', 'épuiser (une ressource)', 'Intensive farming can deplete the soil.', 'L’agriculture intensive peut épuiser les sols.'],
    ['renewable', 'renouvelable', 'Renewable energy now supplies a third of our electricity.', 'Les énergies renouvelables fournissent désormais un tiers de notre électricité.'],
    ['biodiversity', 'biodiversité', 'Pesticides are a major threat to biodiversity.', 'Les pesticides sont une menace majeure pour la biodiversité.'],
    ['to mitigate', 'atténuer', 'Planting trees can help mitigate the effects of flooding.', 'Planter des arbres peut aider à atténuer les effets des inondations.'],
    ['drought', 'sécheresse', 'The region is facing its worst drought in decades.', 'La région connaît sa pire sécheresse depuis des décennies.'],
    ['to phase out', 'supprimer progressivement', 'The country plans to phase out coal by 2030.', 'Le pays prévoit d’abandonner progressivement le charbon d’ici 2030.'],
    ['emissions', 'émissions', 'Transport accounts for a quarter of emissions.', 'Les transports représentent un quart des émissions.'],
    ['sustainable', 'durable', 'We need a more sustainable model of growth.', 'Nous avons besoin d’un modèle de croissance plus durable.'],
    ['to offset', 'compenser', 'Some airlines let passengers offset their emissions.', 'Certaines compagnies permettent aux passagers de compenser leurs émissions.'],
    ['tipping point', 'point de bascule', 'Scientists warn that we are nearing a tipping point.', 'Les scientifiques avertissent que nous approchons d’un point de bascule.'],
    ['landfill', 'décharge, enfouissement', 'Most of this plastic ends up in landfill.', 'La plupart de ce plastique finit en décharge.'],
    ['to dispose of', 'se débarrasser de, éliminer', 'It is hard to dispose of nuclear waste safely.', 'Il est difficile d’éliminer les déchets nucléaires en toute sécurité.'],
    ['habitat', 'habitat (naturel)', 'Deforestation is destroying the orangutan’s habitat.', 'La déforestation détruit l’habitat de l’orang-outan.'],
    ['to harness', 'exploiter, capter (une énergie)', 'Engineers are finding new ways to harness tidal power.', 'Les ingénieurs trouvent de nouveaux moyens d’exploiter l’énergie marémotrice.'],
    ['pollutant', 'polluant', 'Nitrogen dioxide is a common urban pollutant.', 'Le dioxyde d’azote est un polluant urbain courant.'],
    ['to dwindle', 'diminuer, s’amenuiser', 'Fish stocks continue to dwindle.', 'Les stocks de poissons continuent de diminuer.'],
    ['greenwashing', 'écoblanchiment', 'The advert was criticised as pure greenwashing.', 'La publicité a été critiquée comme du pur écoblanchiment.'],
    ['to replenish', 'reconstituer, réapprovisionner', 'Heavy rain helped replenish the reservoirs.', 'De fortes pluies ont aidé à reconstituer les réserves d’eau.'],
    ['wildlife', 'faune sauvage', 'The new motorway will cut through an important wildlife corridor.', 'La nouvelle autoroute traversera un important corridor pour la faune sauvage.'],
  ],
  c1_mind: [
    ['resilient', 'résilient, qui tient le coup', 'Children are often more resilient than we think.', 'Les enfants sont souvent plus résilients qu’on ne le pense.'],
    ['complacent', 'trop sûr de soi, qui se repose sur ses lauriers', 'We cannot afford to be complacent about security.', 'Nous ne pouvons pas nous permettre de relâcher notre vigilance en matière de sécurité.'],
    ['outspoken', 'franc, qui a son franc-parler', 'She is an outspoken critic of the reform.', 'Elle critique ouvertement la réforme.'],
    ['to dwell on', 'ressasser, s’attarder sur', 'Try not to dwell on past mistakes.', 'Essaie de ne pas ressasser tes erreurs passées.'],
    ['conscientious', 'consciencieux', 'He is a conscientious and reliable employee.', 'C’est un employé consciencieux et fiable.'],
    ['wary of', 'méfiant à l’égard de', 'Investors are wary of the new regulations.', 'Les investisseurs se méfient de la nouvelle réglementation.'],
    ['to resent', 'en vouloir à, mal supporter', 'Many staff resent the new monitoring software.', 'Beaucoup d’employés supportent mal le nouveau logiciel de surveillance.'],
    ['self-effacing', 'effacé, modeste', 'Despite his success, he remains self-effacing.', 'Malgré son succès, il reste modeste.'],
    ['dismissive', 'dédaigneux', 'The manager was dismissive of our suggestions.', 'Le manager a balayé nos suggestions avec dédain.'],
    ['to come to terms with', 'accepter, se faire à', 'It took her years to come to terms with the loss.', 'Il lui a fallu des années pour accepter cette perte.'],
    ['level-headed', 'pondéré, posé', 'We need someone level-headed in a crisis.', 'Il nous faut quelqu’un de posé en cas de crise.'],
    ['apprehensive', 'inquiet, appréhensif', 'I was a little apprehensive about the interview.', 'J’appréhendais un peu l’entretien.'],
    ['to take for granted', 'considérer comme acquis', 'Never take for granted the people who support you.', 'Ne considère jamais comme acquis les gens qui te soutiennent.'],
    ['earnest', 'sérieux, sincère', 'He made an earnest attempt to apologise.', 'Il a sincèrement essayé de s’excuser.'],
    ['to bear a grudge', 'garder rancune', 'She is not the kind of person to bear a grudge.', 'Elle n’est pas du genre à garder rancune.'],
    ['headstrong', 'têtu, obstiné', 'As a teenager, he was headstrong and impulsive.', 'Adolescent, il était têtu et impulsif.'],
    ['gullible', 'crédule', 'Scammers target gullible users online.', 'Les escrocs ciblent les internautes crédules.'],
    ['to keep a low profile', 'se faire discret', 'After the scandal, he decided to keep a low profile.', 'Après le scandale, il a décidé de se faire discret.'],
    ['meticulous', 'méticuleux', 'She keeps meticulous records of every transaction.', 'Elle tient un registre méticuleux de chaque transaction.'],
    ['ambivalent', 'partagé, ambivalent', 'Voters remain ambivalent about the proposal.', 'Les électeurs restent partagés sur la proposition.'],
  ],
  c1_idioms: [
    ['a blessing in disguise', 'un mal pour un bien', 'Losing that job was a blessing in disguise.', 'Perdre ce travail a été un mal pour un bien.'],
    ['to cut corners', 'bâcler, rogner sur la qualité', 'Never cut corners when it comes to safety.', 'Ne bâcle jamais rien quand il s’agit de sécurité.'],
    ['the tip of the iceberg', 'la partie émergée de l’iceberg', 'These cases are just the tip of the iceberg.', 'Ces cas ne sont que la partie émergée de l’iceberg.'],
    ['to sit on the fence', 'ne pas prendre parti', 'You can’t sit on the fence forever.', 'Tu ne peux pas rester neutre éternellement.'],
    ['to bite the bullet', 'se résoudre à faire quelque chose de pénible', 'We’ll have to bite the bullet and raise prices.', 'Nous allons devoir nous résoudre à augmenter les prix.'],
    ['back to the drawing board', 'retour à la case départ', 'The client rejected it, so it’s back to the drawing board.', 'Le client l’a refusé, donc retour à la case départ.'],
    ['to cost an arm and a leg', 'coûter les yeux de la tête', 'Repairs like that cost an arm and a leg.', 'Ce genre de réparation coûte les yeux de la tête.'],
    ['to stand someone up', 'poser un lapin à quelqu’un', 'It’s rude to stand someone up without a message.', 'C’est impoli de poser un lapin à quelqu’un sans prévenir.'],
    ['to call it a day', 's’arrêter là (pour aujourd’hui)', 'It’s getting late, so let’s call it a day.', 'Il se fait tard, alors arrêtons-nous là.'],
    ['in the same boat', 'dans la même galère', 'Don’t worry, we’re all in the same boat.', 'Ne t’inquiète pas, nous sommes tous dans la même galère.'],
    ['to go the extra mile', 'faire un effort supplémentaire', 'Our staff always go the extra mile for customers.', 'Notre personnel fait toujours un effort supplémentaire pour les clients.'],
    ['to get the hang of', 'prendre le coup de main', 'It takes a while to get the hang of the new software.', 'Il faut un moment pour prendre le coup de main avec le nouveau logiciel.'],
    ['on the same page', 'sur la même longueur d’onde', 'Let’s make sure we’re on the same page before the meeting.', 'Assurons-nous d’être sur la même longueur d’onde avant la réunion.'],
    ['the last straw', 'la goutte d’eau qui fait déborder le vase', 'The latest delay was the last straw.', 'Le dernier retard a été la goutte d’eau qui fait déborder le vase.'],
    ['to break the ice', 'briser la glace', 'A short game helped break the ice.', 'Un petit jeu a aidé à briser la glace.'],
    ['to hit the nail on the head', 'mettre le doigt dessus', 'You hit the nail on the head with that comment.', 'Tu as mis le doigt dessus avec cette remarque.'],
    ['in the loop', 'au courant, informé', 'Please keep me in the loop.', 'Tiens-moi au courant, s’il te plaît.'],
    ['a long shot', 'un pari risqué, peu de chances', 'It’s a long shot, but it might work.', 'Il y a peu de chances, mais ça pourrait marcher.'],
    ['to play it by ear', 'improviser, aviser', 'We don’t have a plan yet, so we’ll play it by ear.', 'Nous n’avons pas encore de plan, donc nous aviserons.'],
    ['up in the air', 'en suspens, incertain', 'Our holiday plans are still up in the air.', 'Nos projets de vacances sont encore incertains.'],
  ],
};
