import type { VocabRow } from '../level';
import { vocabFromRows } from '../level';

/** Thèmes de vocabulaire B1 ; l'ordre des thèmes = ordre d'apprentissage. */
export const THEMES_B1: Record<string, string> = {
  b1_work: 'Travail et carrière',
  b1_studies: 'Études et formation',
  b1_travel: 'Voyages et tourisme',
  b1_health: 'Santé et mode de vie',
  b1_media: 'Médias et technologie',
  b1_relationships: 'Relations et sentiments',
};

const ROWS: Record<string, VocabRow[]> = {
  b1_work: [
    ['to apply for a job', 'postuler à un emploi', 'She applied for a job at a bank.', 'Elle a postulé à un emploi dans une banque.'],
    ['a job interview', 'un entretien d’embauche', 'I have a job interview on Monday.', 'J’ai un entretien d’embauche lundi.'],
    ['a candidate', 'un candidat, une candidate', 'We interviewed five candidates.', 'Nous avons reçu cinq candidats en entretien.'],
    ['a salary', 'un salaire', 'The salary is better than in my last job.', 'Le salaire est meilleur que dans mon dernier emploi.'],
    ['a deadline', 'une date limite, une échéance', 'The deadline for the project is Friday.', 'La date limite du projet est vendredi.'],
    ['a colleague', 'un ou une collègue', 'My colleagues are very helpful.', 'Mes collègues sont très serviables.'],
    ['to be in charge of', 'être responsable de', 'He’s in charge of the marketing team.', 'Il est responsable de l’équipe marketing.'],
    ['to get promoted', 'obtenir une promotion', 'She got promoted after two years.', 'Elle a obtenu une promotion au bout de deux ans.'],
    ['to resign', 'démissionner', 'He resigned because of the long hours.', 'Il a démissionné à cause des horaires trop longs.'],
    ['to hire', 'embaucher', 'The company is hiring new staff.', 'L’entreprise embauche du personnel.'],
    ['to be fired', 'être renvoyé, être licencié', 'He was fired for being late every day.', 'Il a été renvoyé parce qu’il était en retard tous les jours.'],
    ['full-time', 'à temps plein', 'I work full-time in an office.', 'Je travaille à temps plein dans un bureau.'],
    ['part-time', 'à temps partiel', 'She has a part-time job in a café.', 'Elle a un emploi à temps partiel dans un café.'],
    ['to work from home', 'télétravailler', 'I work from home on Fridays.', 'Je télétravaille le vendredi.'],
    ['a meeting', 'une réunion', 'The meeting has been moved to 3 pm.', 'La réunion a été déplacée à 15 h.'],
    ['to set up a business', 'créer une entreprise', 'They set up a business together after university.', 'Ils ont créé une entreprise ensemble après la fac.'],
    ['experience', 'l’expérience (professionnelle)', 'Do you have any experience in sales?', 'As-tu de l’expérience dans la vente ?'],
    ['skills', 'les compétences', 'This job requires good communication skills.', 'Ce poste exige de bonnes compétences en communication.'],
    ['a CV', 'un CV', 'Send us your CV and a cover letter.', 'Envoyez-nous votre CV et une lettre de motivation.'],
    ['to retire', 'prendre sa retraite', 'My father retired last year.', 'Mon père a pris sa retraite l’an dernier.'],
  ],
  b1_studies: [
    ['to take an exam', 'passer un examen', 'We take the final exam in June.', 'Nous passons l’examen final en juin.'],
    ['to pass an exam', 'réussir un examen', 'She passed all her exams.', 'Elle a réussi tous ses examens.'],
    ['to fail an exam', 'rater un examen', 'He failed his maths exam.', 'Il a raté son examen de maths.'],
    ['a degree', 'un diplôme universitaire', 'She has a degree in biology.', 'Elle a une licence de biologie.'],
    ['to graduate', 'obtenir son diplôme', 'I graduated three years ago.', 'J’ai obtenu mon diplôme il y a trois ans.'],
    ['a course', 'un cours, une formation', 'I’m doing an online course in design.', 'Je suis une formation en ligne en design.'],
    ['to revise', 'réviser', 'I need to revise for my exam.', 'Je dois réviser pour mon examen.'],
    ['a grade', 'une note', 'I got a good grade in English.', 'J’ai eu une bonne note en anglais.'],
    ['a lecture', 'un cours magistral, une conférence', 'The lecture starts at nine.', 'Le cours magistral commence à neuf heures.'],
    ['a lecturer', 'un ou une enseignante à l’université', 'Our lecturer explains things clearly.', 'Notre enseignant explique les choses clairement.'],
    ['an assignment', 'un devoir, un travail à rendre', 'I have to finish my assignment tonight.', 'Je dois finir mon devoir ce soir.'],
    ['to hand in', 'rendre (un travail)', 'Please hand in your essays on Monday.', 'Merci de rendre vos dissertations lundi.'],
    ['a scholarship', 'une bourse d’études', 'She won a scholarship to study in Canada.', 'Elle a obtenu une bourse pour étudier au Canada.'],
    ['to enrol', 's’inscrire', 'You can enrol online until September.', 'Tu peux t’inscrire en ligne jusqu’en septembre.'],
    ['a timetable', 'un emploi du temps', 'Have you seen the new timetable?', 'As-tu vu le nouvel emploi du temps ?'],
    ['to make progress', 'faire des progrès', 'You’ve made a lot of progress this year.', 'Tu as fait beaucoup de progrès cette année.'],
    ['to look up', 'chercher (un mot, une info)', 'Look up the word in the dictionary.', 'Cherche le mot dans le dictionnaire.'],
    ['knowledge', 'les connaissances, le savoir', 'Travelling improves your knowledge of the world.', 'Voyager améliore ta connaissance du monde.'],
    ['to learn by heart', 'apprendre par cœur', 'We had to learn the poem by heart.', 'Nous avons dû apprendre le poème par cœur.'],
    ['a mistake', 'une erreur', 'Everyone makes mistakes.', 'Tout le monde fait des erreurs.'],
  ],
  b1_travel: [
    ['to book', 'réserver', 'We booked a room near the beach.', 'Nous avons réservé une chambre près de la plage.'],
    ['a return ticket', 'un billet aller-retour', 'A return ticket to Oxford, please.', 'Un aller-retour pour Oxford, s’il vous plaît.'],
    ['a one-way ticket', 'un aller simple', 'I only need a one-way ticket.', 'Je n’ai besoin que d’un aller simple.'],
    ['to check in', 's’enregistrer', 'You can check in online the day before.', 'Tu peux t’enregistrer en ligne la veille.'],
    ['to check out', 'libérer la chambre', 'We have to check out by eleven.', 'Nous devons libérer la chambre avant onze heures.'],
    ['a delay', 'un retard', 'There’s a two-hour delay on our flight.', 'Il y a deux heures de retard sur notre vol.'],
    ['cancelled', 'annulé', 'Our train was cancelled because of the strike.', 'Notre train a été annulé à cause de la grève.'],
    ['luggage', 'les bagages', 'How much luggage can I take?', 'Combien de bagages puis-je emporter ?'],
    ['a boarding pass', 'une carte d’embarquement', 'Please show your boarding pass at the gate.', 'Merci de présenter votre carte d’embarquement à la porte.'],
    ['to set off', 'partir, se mettre en route', 'We set off early to avoid the traffic.', 'Nous sommes partis tôt pour éviter les bouchons.'],
    ['a guided tour', 'une visite guidée', 'The guided tour lasts an hour.', 'La visite guidée dure une heure.'],
    ['to go sightseeing', 'faire du tourisme, visiter', 'We went sightseeing all day.', 'Nous avons visité la ville toute la journée.'],
    ['accommodation', 'l’hébergement', 'Accommodation in the city centre is expensive.', 'L’hébergement en centre-ville est cher.'],
    ['a souvenir', 'un souvenir (objet)', 'I bought a few souvenirs for my family.', 'J’ai acheté quelques souvenirs pour ma famille.'],
    ['abroad', 'à l’étranger', 'Have you ever lived abroad?', 'As-tu déjà vécu à l’étranger ?'],
    ['a destination', 'une destination', 'Portugal is a popular destination.', 'Le Portugal est une destination prisée.'],
    ['to get lost', 'se perdre', 'We got lost in the old town.', 'Nous nous sommes perdus dans la vieille ville.'],
    ['a currency', 'une monnaie, une devise', 'What’s the local currency?', 'Quelle est la monnaie locale ?'],
    ['jet lag', 'le décalage horaire (la fatigue)', 'I still have jet lag after my trip to Tokyo.', 'Je souffre encore du décalage horaire après mon voyage à Tokyo.'],
    ['a fully booked hotel', 'un hôtel complet', 'Every hotel in town was fully booked.', 'Tous les hôtels de la ville étaient complets.'],
  ],
  b1_health: [
    ['to feel sick', 'avoir la nausée', 'I feel sick after that boat trip.', 'J’ai la nausée après cette sortie en bateau.'],
    ['a headache', 'un mal de tête', 'I’ve had a headache all day.', 'J’ai mal à la tête depuis ce matin.'],
    ['a sore throat', 'un mal de gorge', 'I’ve got a sore throat and a cough.', 'J’ai mal à la gorge et je tousse.'],
    ['a cough', 'une toux', 'That cough sounds bad.', 'Cette toux n’a pas l’air bonne.'],
    ['a prescription', 'une ordonnance', 'The doctor gave me a prescription.', 'Le médecin m’a donné une ordonnance.'],
    ['an appointment', 'un rendez-vous', 'I’ve made an appointment with the dentist.', 'J’ai pris rendez-vous chez le dentiste.'],
    ['to recover', 'se rétablir, guérir', 'She’s recovering from the flu.', 'Elle se remet de la grippe.'],
    ['to get better', 'aller mieux', 'I hope you get better soon.', 'J’espère que tu iras mieux bientôt.'],
    ['to hurt', 'faire mal', 'My back hurts.', 'J’ai mal au dos.'],
    ['an injury', 'une blessure', 'He missed the match because of an injury.', 'Il a manqué le match à cause d’une blessure.'],
    ['to keep fit', 'rester en forme', 'I swim twice a week to keep fit.', 'Je nage deux fois par semaine pour rester en forme.'],
    ['to work out', 's’entraîner, faire du sport', 'I work out at the gym after work.', 'Je m’entraîne à la salle après le travail.'],
    ['a healthy diet', 'une alimentation saine', 'A healthy diet includes lots of vegetables.', 'Une alimentation saine comprend beaucoup de légumes.'],
    ['to put on weight', 'prendre du poids', 'I always put on weight during the holidays.', 'Je prends toujours du poids pendant les vacances.'],
    ['to lose weight', 'perdre du poids', 'He wants to lose weight before the summer.', 'Il veut perdre du poids avant l’été.'],
    ['stress', 'le stress', 'Exercise helps me deal with stress.', 'Le sport m’aide à gérer le stress.'],
    ['to cut down on', 'réduire (sa consommation de)', 'I’m trying to cut down on sugar.', 'J’essaie de réduire le sucre.'],
    ['to give up', 'arrêter, renoncer à', 'She gave up smoking ten years ago.', 'Elle a arrêté de fumer il y a dix ans.'],
    ['a symptom', 'un symptôme', 'What are your symptoms?', 'Quels sont tes symptômes ?'],
    ['allergic to', 'allergique à', 'I’m allergic to cats.', 'Je suis allergique aux chats.'],
  ],
  b1_media: [
    ['to download', 'télécharger', 'You can download the app for free.', 'Tu peux télécharger l’application gratuitement.'],
    ['to upload', 'mettre en ligne', 'She uploads a new video every week.', 'Elle met en ligne une nouvelle vidéo chaque semaine.'],
    ['a password', 'un mot de passe', 'Don’t share your password with anyone.', 'Ne partage ton mot de passe avec personne.'],
    ['to log in', 'se connecter', 'I can’t log in to my account.', 'Je n’arrive pas à me connecter à mon compte.'],
    ['an account', 'un compte', 'Have you created an account yet?', 'As-tu déjà créé un compte ?'],
    ['a headline', 'un gros titre', 'The headline was about the elections.', 'Le gros titre parlait des élections.'],
    ['an article', 'un article', 'I read an interesting article about sleep.', 'J’ai lu un article intéressant sur le sommeil.'],
    ['the news', 'les informations, l’actualité', 'I usually watch the news at eight.', 'Je regarde généralement les informations à vingt heures.'],
    ['a podcast', 'un podcast', 'I listen to a podcast on my way to work.', 'J’écoute un podcast en allant au travail.'],
    ['a subscription', 'un abonnement', 'I cancelled my streaming subscription.', 'J’ai résilié mon abonnement de streaming.'],
    ['to post', 'publier', 'He likes to post photos of his meals.', 'Il aime publier des photos de ses repas.'],
    ['to share', 'partager', 'Can you share the link with me?', 'Tu peux partager le lien avec moi ?'],
    ['a screen', 'un écran', 'I spend too much time in front of a screen.', 'Je passe trop de temps devant un écran.'],
    ['to charge', 'recharger', 'I need to charge my phone.', 'Je dois recharger mon téléphone.'],
    ['a device', 'un appareil', 'You can use the app on any device.', 'Tu peux utiliser l’application sur n’importe quel appareil.'],
    ['to update', 'mettre à jour', 'Remember to update your software.', 'Pense à mettre à jour ton logiciel.'],
    ['fake news', 'les fausses informations', 'It’s not always easy to spot fake news.', 'Ce n’est pas toujours facile de repérer les fausses informations.'],
    ['an advert', 'une publicité', 'There are too many adverts on this website.', 'Il y a trop de publicités sur ce site.'],
    ['a series', 'une série', 'Have you watched that new crime series?', 'As-tu regardé cette nouvelle série policière ?'],
    ['to turn off', 'éteindre', 'Please turn off your phone during the film.', 'Merci d’éteindre ton téléphone pendant le film.'],
  ],
  b1_relationships: [
    ['to get on with', 'bien s’entendre avec', 'Do you get on with your neighbours?', 'Tu t’entends bien avec tes voisins ?'],
    ['to fall out with', 'se brouiller avec', 'He fell out with his best friend.', 'Il s’est brouillé avec son meilleur ami.'],
    ['to make up', 'se réconcilier', 'They argued, but they made up the next day.', 'Ils se sont disputés, mais se sont réconciliés le lendemain.'],
    ['to argue', 'se disputer', 'My neighbours argue all the time.', 'Mes voisins se disputent tout le temps.'],
    ['to trust', 'faire confiance à', 'I trust her completely.', 'Je lui fais entièrement confiance.'],
    ['to rely on', 'compter sur', 'You can always rely on me.', 'Tu peux toujours compter sur moi.'],
    ['to look forward to', 'avoir hâte de', 'I’m looking forward to the weekend.', 'J’ai hâte d’être au week-end.'],
    ['to miss', 'manquer à quelqu’un', 'I miss my friends from university.', 'Mes amis de la fac me manquent.'],
    ['proud of', 'fier de', 'I’m really proud of you.', 'Je suis vraiment {fier|fière} de toi.'],
    ['jealous', 'jaloux', 'He gets jealous very easily.', 'Il devient jaloux très facilement.'],
    ['disappointed', 'déçu', 'I was disappointed with the ending.', 'J’ai été {déçu|déçue} par la fin.'],
    ['embarrassed', 'gêné, embarrassé', 'I was so embarrassed when I forgot her name.', 'J’étais tellement {gêné|gênée} quand j’ai oublié son prénom.'],
    ['worried about', 'inquiet pour', 'She’s worried about her exams.', 'Elle s’inquiète pour ses examens.'],
    ['grateful', 'reconnaissant', 'I’m grateful for your help.', 'Je te suis {reconnaissant|reconnaissante} pour ton aide.'],
    ['a close friend', 'un ami proche, une amie proche', 'Tom is a close friend of mine.', 'Tom est un ami proche.'],
    ['to get married', 'se marier', 'They got married last summer.', 'Ils se sont mariés l’été dernier.'],
    ['to break up', 'rompre, se séparer', 'They broke up after five years.', 'Ils se sont séparés au bout de cinq ans.'],
    ['to apologise', 's’excuser', 'You should apologise to her.', 'Tu devrais t’excuser auprès d’elle.'],
    ['to keep in touch', 'rester en contact', 'Let’s keep in touch!', 'Restons en contact !'],
    ['to have a lot in common', 'avoir beaucoup de points communs', 'We have a lot in common.', 'Nous avons beaucoup de points communs.'],
  ],
};

export const VOCAB_B1 = vocabFromRows('B1', ROWS);
