import type { VocabRow } from '../level';

/** Thèmes de vocabulaire B2, dans l'ordre d'apprentissage. */
export const THEMES_B2: Record<string, string> = {
  b2_work: 'Travail et carrière',
  b2_media: 'Médias et technologie',
  b2_society: 'Société et environnement',
  b2_relationships: 'Relations et émotions',
  b2_phrasal: 'Verbes à particule',
  b2_collocations: 'Collocations et expressions',
};

/** L'exemple contient le mot tel quel quand c'est possible, pour permettre l'exercice à trous généré. */
export const VOCAB_ROWS_B2: Record<string, VocabRow[]> = {
  b2_work: [
    ['deadline', 'échéance, date limite', 'We’re under pressure to meet the deadline.', 'Nous sommes sous pression pour respecter l’échéance.'],
    ['workload', 'charge de travail', 'My workload has doubled since the merger.', 'Ma charge de travail a doublé depuis la fusion.'],
    ['to apply for', 'postuler à, poser sa candidature à', 'I’d like to apply for the marketing position.', 'J’aimerais postuler au poste en marketing.'],
    ['promotion', 'promotion, avancement', 'She got a promotion after only a year.', 'Elle a obtenu une promotion au bout d’un an seulement.'],
    ['pay rise', 'augmentation de salaire', 'I’m going to ask for a pay rise.', 'Je vais demander une augmentation.'],
    ['to resign', 'démissionner', 'He decided to resign after the scandal.', 'Il a décidé de démissionner après le scandale.'],
    ['to be laid off', 'être licencié (pour raisons économiques)', 'Two hundred workers are going to be laid off.', 'Deux cents salariés vont être licenciés.'],
    ['line manager', 'supérieur hiérarchique direct', 'I need to discuss it with my line manager first.', 'Je dois d’abord en parler à mon supérieur.'],
    ['skills', 'compétences', 'The job requires strong communication skills.', 'Le poste exige de solides compétences en communication.'],
    ['background', 'parcours, formation', 'She has a background in engineering.', 'Elle a une formation d’ingénieure.'],
    ['flexible hours', 'horaires flexibles', 'The company offers flexible hours and remote work.', 'L’entreprise propose des horaires flexibles et du télétravail.'],
    ['remote work', 'télétravail', 'Remote work has changed the way we hold meetings.', 'Le télétravail a changé notre façon de faire des réunions.'],
    ['shortlist', 'liste des candidats retenus', 'Only five candidates are on the shortlist.', 'Seuls cinq candidats ont été présélectionnés.'],
    ['self-employed', 'indépendant, à son compte', 'My sister has been self-employed for ten years.', 'Ma sœur est à son compte depuis dix ans.'],
    ['to run a business', 'diriger une entreprise', 'It’s hard to run a business and raise a family.', 'C’est difficile de diriger une entreprise et d’élever une famille.'],
    ['career path', 'parcours professionnel', 'He took an unusual career path into teaching.', 'Il a suivi un parcours inhabituel pour devenir enseignant.'],
    ['to take on', 'embaucher ; assumer (une tâche)', 'We’re planning to take on three new engineers.', 'Nous prévoyons d’embaucher trois nouveaux ingénieurs.'],
    ['burnout', 'épuisement professionnel', 'Long hours can lead to burnout.', 'Les longues journées peuvent mener à l’épuisement professionnel.'],
    ['appraisal', 'entretien annuel d’évaluation', 'My annual appraisal is next Tuesday.', 'Mon entretien annuel est mardi prochain.'],
    ['notice period', 'préavis', 'My notice period is three months.', 'Mon préavis est de trois mois.'],
  ],
  b2_media: [
    ['headline', 'gros titre', 'Did you see the headline in today’s paper?', 'Tu as vu le gros titre dans le journal d’aujourd’hui ?'],
    ['breaking news', 'dernières nouvelles, flash info', 'We interrupt this programme for some breaking news.', 'Nous interrompons ce programme pour un flash info.'],
    ['fake news', 'fausses informations', 'Fake news spreads faster than the truth online.', 'Les fausses informations se propagent plus vite que la vérité en ligne.'],
    ['reliable source', 'source fiable', 'Always check that the article comes from a reliable source.', 'Vérifie toujours que l’article provient d’une source fiable.'],
    ['bias', 'parti pris, biais', 'The report was criticised for its political bias.', 'Le rapport a été critiqué pour son parti pris politique.'],
    ['coverage', 'couverture médiatique', 'The election received huge media coverage.', 'L’élection a bénéficié d’une énorme couverture médiatique.'],
    ['to go viral', 'devenir viral, faire le buzz', 'Nobody expected the video to go viral.', 'Personne ne s’attendait à ce que la vidéo fasse le buzz.'],
    ['influencer', 'influenceur, influenceuse', 'The brand paid an influencer to promote its new phone.', 'La marque a payé une influenceuse pour promouvoir son nouveau téléphone.'],
    ['subscription', 'abonnement', 'I cancelled my subscription to the streaming service.', 'J’ai résilié mon abonnement au service de streaming.'],
    ['privacy', 'vie privée, confidentialité', 'Many users are worried about their privacy online.', 'Beaucoup d’utilisateurs s’inquiètent pour leur vie privée en ligne.'],
    ['data breach', 'fuite de données', 'The bank admitted a data breach affecting thousands of customers.', 'La banque a reconnu une fuite de données touchant des milliers de clients.'],
    ['to update', 'mettre à jour', 'Don’t forget to update the app before the trip.', 'N’oublie pas de mettre à jour l’appli avant le voyage.'],
    ['device', 'appareil', 'You can use the app on any device.', 'Tu peux utiliser l’appli sur n’importe quel appareil.'],
    ['screen time', 'temps d’écran', 'Parents are trying to limit their children’s screen time.', 'Les parents essaient de limiter le temps d’écran de leurs enfants.'],
    ['artificial intelligence', 'intelligence artificielle', 'Artificial intelligence is changing the job market.', 'L’intelligence artificielle transforme le marché du travail.'],
    ['to download', 'télécharger', 'You need to download the report as a PDF.', 'Tu dois télécharger le rapport en PDF.'],
    ['podcast', 'podcast', 'I listen to a history podcast on my way to work.', 'J’écoute un podcast d’histoire en allant au travail.'],
    ['editor', 'rédacteur en chef', 'The editor decided not to publish the story.', 'Le rédacteur en chef a décidé de ne pas publier l’article.'],
    ['to broadcast', 'diffuser, retransmettre', 'The channel plans to broadcast the final live.', 'La chaîne prévoit de retransmettre la finale en direct.'],
    ['clickbait', 'piège à clics', 'That title is pure clickbait.', 'Ce titre est un pur piège à clics.'],
  ],
  b2_society: [
    ['climate change', 'changement climatique', 'Climate change affects farmers first.', 'Le changement climatique touche d’abord les agriculteurs.'],
    ['carbon footprint', 'empreinte carbone', 'Flying less is the easiest way to reduce your carbon footprint.', 'Prendre moins l’avion est le moyen le plus simple de réduire son empreinte carbone.'],
    ['renewable energy', 'énergie renouvelable', 'The country produces half its electricity from renewable energy.', 'Le pays produit la moitié de son électricité à partir d’énergies renouvelables.'],
    ['waste', 'déchets ; gaspillage', 'We need to cut food waste in schools.', 'Nous devons réduire le gaspillage alimentaire dans les écoles.'],
    ['pollution', 'pollution', 'Air pollution is a major problem in big cities.', 'La pollution de l’air est un problème majeur dans les grandes villes.'],
    ['endangered species', 'espèce menacée', 'The snow leopard is an endangered species.', 'La panthère des neiges est une espèce menacée.'],
    ['inequality', 'inégalité', 'The report highlights growing inequality between regions.', 'Le rapport souligne l’inégalité croissante entre les régions.'],
    ['unemployment', 'chômage', 'Unemployment has fallen for the third year in a row.', 'Le chômage a baissé pour la troisième année consécutive.'],
    ['housing', 'logement', 'The lack of affordable housing is pushing families out of the city.', 'Le manque de logements abordables chasse les familles de la ville.'],
    ['to raise awareness', 'sensibiliser', 'The campaign aims to raise awareness of mental health.', 'La campagne vise à sensibiliser à la santé mentale.'],
    ['volunteer', 'bénévole', 'She works as a volunteer at a local food bank.', 'Elle est bénévole dans une banque alimentaire locale.'],
    ['charity', 'association caritative', 'All the money goes to charity.', 'Tout l’argent est reversé à une association caritative.'],
    ['protest', 'manifestation', 'Thousands joined the protest against the new law.', 'Des milliers de personnes ont rejoint la manifestation contre la nouvelle loi.'],
    ['government', 'gouvernement', 'The government has promised to cut taxes.', 'Le gouvernement a promis de baisser les impôts.'],
    ['policy', 'politique, mesure', 'The new policy will come into force in January.', 'La nouvelle mesure entrera en vigueur en janvier.'],
    ['public transport', 'transports en commun', 'Public transport is free for students here.', 'Les transports en commun sont gratuits pour les étudiants ici.'],
    ['ageing population', 'vieillissement de la population', 'An ageing population puts pressure on health services.', 'Le vieillissement de la population met les services de santé sous pression.'],
    ['to recycle', 'recycler', 'This packaging is hard to recycle.', 'Cet emballage est difficile à recycler.'],
    ['sustainable', 'durable (écologique)', 'We’re looking for more sustainable ways to travel.', 'Nous cherchons des façons plus durables de voyager.'],
    ['crime rate', 'taux de criminalité', 'The crime rate has dropped in the city centre.', 'Le taux de criminalité a baissé dans le centre-ville.'],
  ],
  b2_relationships: [
    ['get on well with', 'bien s’entendre avec', 'I get on well with my flatmates.', 'Je m’entends bien avec mes colocataires.'],
    ['fall out with', 'se brouiller avec', 'I don’t want to fall out with you over something so silly.', 'Je ne veux pas me fâcher avec toi pour une chose aussi bête.'],
    ['make up', 'se réconcilier', 'They always argue, but they make up quickly.', 'Ils se disputent tout le temps, mais ils se réconcilient vite.'],
    ['break up', 'rompre, se séparer', 'They decided to break up after five years together.', 'Ils ont décidé de se séparer après cinq ans ensemble.'],
    ['trust', 'confiance', 'Trust takes years to build.', 'La confiance met des années à se construire.'],
    ['supportive', 'qui soutient, encourageant', 'My parents have always been very supportive.', 'Mes parents ont toujours été très présents pour moi.'],
    ['reliable', 'fiable, sur qui on peut compter', 'Tom is the most reliable person I know.', 'Tom est la personne la plus fiable que je connaisse.'],
    ['jealous', 'jaloux, jalouse', 'He gets jealous when she talks to other men.', 'Il devient jaloux quand elle parle à d’autres hommes.'],
    ['upset', 'contrarié, bouleversé', 'She was upset that nobody remembered her birthday.', 'Elle était contrariée que personne ne se souvienne de son anniversaire.'],
    ['grateful', 'reconnaissant', 'We’re really grateful for your help.', 'Nous vous sommes vraiment reconnaissants de votre aide.'],
    ['look up to', 'admirer, prendre pour modèle', 'Many kids look up to their sports heroes.', 'Beaucoup d’enfants admirent leurs héros sportifs.'],
    ['let someone down', 'décevoir quelqu’un, laisser tomber', 'Don’t worry, I won’t let you down.', 'Ne t’inquiète pas, je ne te laisserai pas tomber.'],
    ['bond', 'lien', 'There’s a strong bond between the two brothers.', 'Il y a un lien fort entre les deux frères.'],
    ['argument', 'dispute', 'We had an argument about money.', 'Nous nous sommes disputés à propos d’argent.'],
    ['to apologise', 's’excuser', 'You really need to apologise to her.', 'Tu dois vraiment t’excuser auprès d’elle.'],
    ['flatmate', 'colocataire', 'My flatmate never does the washing-up.', 'Mon colocataire ne fait jamais la vaisselle.'],
    ['acquaintance', 'connaissance (personne)', 'He’s not really a friend, more an acquaintance.', 'Ce n’est pas vraiment un ami, plutôt une connaissance.'],
    ['get along with', 's’entendre avec', 'Do you get along with your in-laws?', 'Tu t’entends avec ta belle-famille ?'],
    ['moody', 'lunatique, d’humeur changeante', 'Teenagers can be quite moody.', 'Les ados peuvent être assez lunatiques.'],
    ['keep in touch', 'rester en contact', 'Let’s keep in touch after the course.', 'Restons en contact après la formation.'],
  ],
  b2_phrasal: [
    ['put off', 'reporter, repousser', 'Let’s put off the meeting until Monday.', 'Reportons la réunion à lundi.'],
    ['carry out', 'réaliser, mener', 'The team will carry out a survey of local residents.', 'L’équipe va mener une enquête auprès des habitants.'],
    ['come up with', 'trouver, imaginer (une idée)', 'We need to come up with a better name.', 'Il faut qu’on trouve un meilleur nom.'],
    ['run out of', 'ne plus avoir de, manquer de', 'We’re about to run out of petrol.', 'Nous allons bientôt tomber en panne d’essence.'],
    ['turn down', 'refuser ; baisser (le son)', 'Why did you turn down such a good offer?', 'Pourquoi as-tu refusé une offre aussi intéressante ?'],
    ['look into', 'examiner, se pencher sur', 'The police are going to look into the matter.', 'La police va se pencher sur l’affaire.'],
    ['give up', 'abandonner, renoncer à', 'Don’t give up now, you’re almost there!', 'N’abandonne pas maintenant, tu y es presque !'],
    ['set up', 'créer, monter (une entreprise)', 'She wants to set up her own company.', 'Elle veut créer sa propre entreprise.'],
    ['figure out', 'comprendre, trouver (la solution)', 'I can’t figure out how this machine works.', 'Je n’arrive pas à comprendre comment marche cette machine.'],
    ['bring up', 'aborder (un sujet) ; élever (un enfant)', 'Don’t bring up politics at dinner.', 'N’aborde pas la politique au dîner.'],
    ['get over', 'se remettre de', 'It took her weeks to get over the flu.', 'Il lui a fallu des semaines pour se remettre de la grippe.'],
    ['take up', 'se mettre à (une activité)', 'I’ve decided to take up yoga.', 'J’ai décidé de me mettre au yoga.'],
    ['point out', 'faire remarquer, signaler', 'I’d like to point out a mistake in the report.', 'J’aimerais signaler une erreur dans le rapport.'],
    ['call off', 'annuler', 'They had to call off the match because of the snow.', 'Ils ont dû annuler le match à cause de la neige.'],
    ['go through', 'examiner en détail ; traverser (une épreuve)', 'Let’s go through the contract together.', 'Examinons le contrat ensemble.'],
    ['catch up', 'prendre des nouvelles ; rattraper son retard', 'Let’s meet for coffee and catch up.', 'Retrouvons-nous pour un café et prenons des nouvelles.'],
    ['work out', 'faire du sport ; trouver (une solution)', 'I work out at the gym three times a week.', 'Je fais du sport à la salle trois fois par semaine.'],
    ['get back to', 'recontacter, revenir vers', 'I’ll get back to you by the end of the day.', 'Je reviens vers vous d’ici la fin de la journée.'],
    ['sort out', 'régler, arranger', 'Don’t worry, we’ll sort out the problem tomorrow.', 'Ne t’inquiète pas, on réglera le problème demain.'],
    ['back up', 'sauvegarder ; soutenir', 'Always back up your files before an update.', 'Sauvegarde toujours tes fichiers avant une mise à jour.'],
  ],
  b2_collocations: [
    ['make a decision', 'prendre une décision', 'We have to make a decision today.', 'Nous devons prendre une décision aujourd’hui.'],
    ['make progress', 'progresser, faire des progrès', 'It takes time to make progress in a language.', 'Il faut du temps pour progresser dans une langue.'],
    ['do research', 'faire des recherches', 'I need to do research before I buy a car.', 'Je dois me renseigner avant d’acheter une voiture.'],
    ['take a risk', 'prendre un risque', 'Sometimes you have to take a risk.', 'Parfois, il faut prendre un risque.'],
    ['meet a deadline', 'respecter une échéance', 'It was hard to meet a deadline that tight.', 'C’était difficile de respecter une échéance aussi serrée.'],
    ['pay attention', 'faire attention', 'Please pay attention to the safety instructions.', 'Merci de faire attention aux consignes de sécurité.'],
    ['make an effort', 'faire un effort', 'He didn’t even make an effort to be polite.', 'Il n’a même pas fait l’effort d’être poli.'],
    ['take into account', 'prendre en compte', 'We must take into account the cost of transport.', 'Nous devons prendre en compte le coût du transport.'],
    ['reach an agreement', 'parvenir à un accord', 'The two sides finally managed to reach an agreement.', 'Les deux parties ont enfin réussi à parvenir à un accord.'],
    ['run a risk', 'courir un risque', 'If you don’t back up your files, you run a risk of losing everything.', 'Si tu ne sauvegardes pas tes fichiers, tu cours le risque de tout perdre.'],
    ['keep an eye on', 'surveiller, garder un œil sur', 'Can you keep an eye on my bag for a minute?', 'Tu peux surveiller mon sac une minute ?'],
    ['come to a conclusion', 'arriver à une conclusion', 'It’s too early to come to a conclusion.', 'Il est trop tôt pour tirer une conclusion.'],
    ['raise a question', 'soulever une question', 'I’d like to raise a question about the budget.', 'J’aimerais soulever une question sur le budget.'],
    ['heavy traffic', 'circulation dense', 'We were stuck in heavy traffic for an hour.', 'Nous sommes restés bloqués dans les embouteillages pendant une heure.'],
    ['strong coffee', 'café fort, serré', 'I need a strong coffee before the meeting.', 'J’ai besoin d’un café bien fort avant la réunion.'],
    ['highly recommended', 'vivement recommandé', 'The restaurant is highly recommended by locals.', 'Le restaurant est vivement recommandé par les habitants.'],
    ['bitterly disappointed', 'profondément déçu', 'The fans were bitterly disappointed by the result.', 'Les supporters ont été profondément déçus par le résultat.'],
    ['catch a cold', 'attraper un rhume', 'Wrap up warm or you’ll catch a cold.', 'Couvre-toi bien, sinon tu vas attraper un rhume.'],
    ['break the news', 'annoncer la nouvelle', 'How are we going to break the news to the team?', 'Comment allons-nous annoncer la nouvelle à l’équipe ?'],
    ['a matter of time', 'une question de temps', 'It’s only a matter of time before prices go up.', 'Ce n’est qu’une question de temps avant que les prix augmentent.'],
  ],
};
